### ISSUE TITLE
Some handy functions

### ISSUE THREAD

**Issue by EduardoVB** [WaynePhillipsEA/twinbasic#102]
**Is your feature request related to a problem? Please describe.**

There are some functions that are too frequently necessary, and VB6 lacks of them.
I'm opening this issue as possible discussion, not a request per se.
And also, considering issue #101 

I've made a component that adds all these functions, but that requires to add a dependency.
If dependencies are handled someway in tB that don't require to add a dll file, and a manifest, that would be great (I'm still not familiar with that subject).
But in VB6 it raises some complication to add such dependencies, so many times I thought: why didn't they add these to the language?

**Describe the solution you'd like**

Some of these functions are:

Function IsInArray (item) As Boolean
Returns if the item (generaly a String or a number) is already in the array

Sub AddToArray (array, item, Optional OnlyIfNotExists As Boolean)
Redims the array and adds the item at the end.
Of course rediming an array for every new element is not efficient at all, but it is intended for small lists (between 5 and 100 items) that you usually don't know in advance how many elements they will be.

Function IndexInArray(array, item) As Long
Returns the index of an item in an array, or -1 if it does not exist. OK, my "convention" is that my arrays start with index 0.

These three functions above, greatly sped up my programming.

Others often needed:

Function GetFolder(path As String ) As String
Returns the folder part of a path

Function GetFileName(path as String) As String    (or simply named FileName)
Returns the file name part

Function FileExists(path) As Boolean
Returns if a file exists.

Function FolderExists(path) As Boolean
Returns if a folder exists.

Also a function that is not mine, but very much needed:

Function InIDE() As Boolean
Returns whether we are running in source code or compiled.
But the name should be IsCompiled, because a component can run compiled in IDE.

Sub SaveTextFile(path, text)
Saves a text file

Sub SaveBinaryFile(path, bytes())
Saves a binary file

Function Trim2(text As String) as String   (or another name, like TrimAll, TrimMore)
It trims not only spaces, but also tabs, CR and LF (and might be null chars could also be included)

Function IsFormLoaded(form) As Boolean
if the form argument is an Object type (Form, Object) it looks for the form instance, if it is a String, it looks for any instance of that form name.

Function WordCount() As Long
Returns the number of words

Sub ActivatePrevInstance
It may seem simple, but it has some complexity to do it right. The app may be minimized to the system tray, or may be hanged.

They are not needed all the time, but when you have them (as long as you remember that you have them), they speed up the programming.

Specially the ones to work with arrays were very useful to me.

**Comment by Kr00l** [comment]
IMO the functions that I would support to be added are rather low-level, e.g my #99 bid.
However, while I did that. I certainly disagree IMO for highler level "generic" functions.
We, VB6 guys, are already used to ship a "common.bas" around and re-use everywhere.
Because if tB opens this Box there will always coming "more requests" and bloating up the namespaces.
However, as said, some additions I would welcome if they are low-level and very clear.

**Comment by bclothier** [comment]
FWIW, that is the problem that #16 will help solve. Instead of having everyone author their own versions of `common.bas` that all does same thing little differently, everyone should be able to get the required functionalities from a package manager, and only that for their specific domain. The common library doesn't have to be one giant toolbox with every tools imaginable. Rather, it should be divided into concise groups of functionalities and pulled in where it is actually needed. 

IMO, one big reason for resisting adding more to references was because of VB*'s horrid handling of references where full path were used and registry was consulted. With a good implementation of #16, those problems will disappear and we can include as many packages as we need without having to reinvent the wheels all the time.

**Comment by EduardoVB** [comment]
> Because if tB opens this Box there will always coming "more requests" and bloating up the namespaces. That's why I close my #99 as I will just continue then to have my own bas solution.

OK, I'll close this one too.

It can be handled if #16 is implemented.
Thank you.
