### ISSUE TITLE
Automatically add block closing as you type

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#13]
**Is your feature request related to a problem? Please describe.**
When adding block elements, twinBASIC should automatically add the end block statement once the developer has typed the opening statement

**Describe the solution you'd like**
After typing the opening statement, such as 'Public Sub DoSomething()', twinBASIC should add the 'End Sub' underneath it in order to complete the block automatically. 

**Additional context**
VB6/VBA does this for Sub/Function/Property, but all block level elements should be considered, e.g. For->Next, With->End With, etc

**Comment by retailcoder** [comment]
The more twinBASIC I write, the more I'm finding this feature would make the compiler feel more resilient and stable overall, since adding a code block without closing it entails a ton of sudden compiler errors and generates lots of noise in the analyzers - I suppose simply having the ability to move modules/components into separate source files would already help, but regardless...

If new blocks closed themselves (with the caret auto-indented just where it needs to be!) *before* the compiler started a parse run, it seems *a lot* of cycles would be spared between the moment <kbd>ENTER</kbd> is pressed to open that block and the moment the user starts typing the first few characters inside that block.

There's a lot more to this feature than a mere little convenient UX enhancement.

**Comment by WaynePhillipsEA** [comment]
This was included in v0.10.3212, apologies for the late closing of the issue.
