### ISSUE TITLE
Allow IsMissing for non variant variables

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#213]
The IsMissing function of VBA only works with Optional Variant variables.  Is it possible to extend the scope of IsMissing to include non variant variables.  If it is not possible to revise IsMissing could an alternative IsAbsent function be made available.

I appreciate that the availability of overloading might make this request unviable.

**Comment by WaynePhillipsEA** [comment]
No, sorry, we can't do that.  With Variants, missing arguments are passed from the caller as a special value so that the callee can use IsMissing on them.  For non-Variant arguments, the caller just passes the default value (or the implicit default value if not defined), and so the callee cannot know whether or not the caller passed the value explicitly or not.  

Only Variants allow us to hold the extra information needed to know if the provided argument was missing or not.
