### ISSUE TITLE
malicious activity

### ISSUE THREAD

**Issue by alberto-gilman** [WaynePhillipsEA/twinbasic#222]
I don't think it is a bug but is a great problem, I created the simplest exe project, this is all the code:

`Module MainModule

    ' This project type is set to 'Standard EXE' in the Settings file, so you need a Main() subroutine to run when the EXE is started.
    Public Sub Main()
    End Sub
	
End Module
`
Compile and run the project, and Cortex XDR detect it as malicious activity

![imagen](https://user-images.githubusercontent.com/63146080/121894521-855bd380-cd1f-11eb-9d05-e1e6711226fc.png)

the details data:
Información de la aplicación:
ID de proceso:	21780
Ubicación de aplicaciones:	C:\Basura\Build\NewProject_win32.exe
Línea de comando:	"c:\Basura\Build\NewProject_win32.exe" 
Origen del archivo:	Unidad de disco duro de este ordenador

Información de la prevención:
Fecha de prevención:	lunes, 14 de junio de 2021
Tiempo de prevención:	14:41:42
Versión de SO:	10.0.19041.2.0.0.256.1
Componente:	Análisis Local
Código de Cortex XDR:	c0400055
Descripción de la prevención:	Detectado ejecutable sospechoso
Información adicional 1:	C:\Basura\Build\NewProject_win32.exe
Información adicional 2:	357FB50EC4458BACEDE608071DC8D3133B405D4156D7E1FE97F91B91429871BD
Información adicional 3:	357FB50EC4458BACEDE608071DC8D3133B405D4156D7E1FE97F91B91429871BD
Información adicional 4:	1
Información adicional 5:	AF037BA6B6C07A1B48AB000004000000000000000006000E0140042200220201

**Comment by alberto-gilman** [comment]
I forgot to put the compiler version:

Version: 0.10.1604

**Comment by WaynePhillipsEA** [comment]
It is a false positive.   All development environments that generate EXEs/DLL suffer from similar problems, even the big names.  On my machine, I have to exclude the EXE output paths in AVAST even when working with Visual Studio, otherwise I constantly get messages about the generated executables being unsafe.

You'll need to add an exclusion to your anti-virus software so that the path where the EXE file is being built is not monitored.
