### ISSUE TITLE
DefType statement is not recognised

### ISSUE THREAD

**Issue by mansellan** [WaynePhillipsEA/twinbasic#23]
**Describe the bug**
DefType is not currently supported.

**To Reproduce**
Try to use any DefType statement (e.g. DefBool) in a standard module

**Expected behavior**
DefType should be recognised and act according to [the docs](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/deftype-statements)

**Desktop**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1602

**Additional context**
Although a legacy (and unloved) feature, for 100% compatibility it would need to be supported

**Comment by wqweto** [comment]
An option is to restrict `DefXxx` to the special `A-Z` interval only without handling other custom exotic intervals at all as these are quite rare (never seen one in actual code). `A-Z` is special as it includes all variables even ones that do not start with a letter within `A-Z` interval.

We use `DefObj A-Z` to detect untyped variables/functions which start fail violently at runtime contrary to silentrly being accepted when typed `As Variant` by default (because `Empty` value can be implicitly cast to every other type).

Another option is to parse but ignore `DefXxx` statements altogether but implement warning on untyped variables/functions. This would be a noise warning though :-))

**Comment by mansellan** [comment]
@wqweto A restriction to the use-case you mention wouldn't be enough to fulfill the "100% compatible" goal of twinBASIC. To get to 100%, every crazy edge case has to (eventually) be supported, warts and all. Rubberduck has similar constraints - if it's legal VBA / VB6, we support it no matter how inadvisable it might be. A bunch of our inspections and unit tests are dedicated to extreme edge cases that should never be seen in the wild.

For your specific use-case though, it sounds like [#33: Option Strict](https://github.com/WaynePhillipsEA/twinbasic/issues/33) may be a better alternative once it's available. (I realise this issue predates #33).

**Comment by WaynePhillipsEA** [comment]
All DefTypes are now supported, as of v0.10.800
DefBool/DefByte/DefInt/DefLng/DefLngLng/DefLngPtr/DefSng/DefDbl/DefDate/DefCur/DefDec/DefStr/DefObj/DefVar

**Comment by mburns08109** [comment]
> All DefTypes are now supported, as of v0.10.800
> DefBool/DefByte/DefInt/DefLng/DefLngLng/DefLngPtr/DefSng/DefDbl/DefDate/DefCur/DefDec/DefStr/DefObj/DefVar

OMG! Surely, You're joking.
They actually aded DefLngLng and DefLngPtr to the language in VBA7!??
What an absolutely complete waste of time and effort THAT was!
