### ISSUE TITLE
TypeOf causes compilation error

### ISSUE THREAD

**Issue by uwbwsvd** [WaynePhillipsEA/twinbasic#243]
Dim by As Byte
.....
Debug.Print **TypeOf** by Is Byte

 - twinBASIC compiler version v0.10.2781

**Comment by camomille22003** [comment]
As in VB6 !!!!!

![TypeOf](https://user-images.githubusercontent.com/33807881/123535427-fb026f00-d723-11eb-882e-5a5bb7159e5d.jpg)

**Comment by WaynePhillipsEA** [comment]
The issue here was that in tB we weren't getting the error information properly in the VS Code editor, but instead getting a 'COMPILATION ERROR' code-generation error when attempting to run the code.   Fixed in v0.10.2799 where the compilation error is now properly shown in the editor.  Thanks for reporting.
