### ISSUE TITLE
Allow for compile-time and/or runtime resolution of form and control properties

### ISSUE THREAD

**Issue by mwolfe02** [WaynePhillipsEA/twinbasic#271]
**Is your feature request related to a problem? Please describe.**
In Microsoft Access, I find it frustrating to have to hard-code certain form properties, such as background colors, textbox margins, etc.  This makes it more difficult to maintain consistency across the user interface.  It also makes it more difficult to implement widespread changes.

**Describe the solution you'd like**
Allow one or more of the following options when defining form and control properties (margins, colors, alignment, formatting, etc.):

- Compiler constants:  _(for compile-time resolution of properties) e.g., a common form background color, a common highlight color, etc._
- Global functions: _e.g., `GetHighlightColorBasedOnGoalProgress()`_
- Form-level public functions
- Callback functions: _the callback function would need to accept a relevant set of parameters (e.g., the form object, the control object, the property name, etc.)_

**Describe alternatives you've considered**
Visual styles may provide much of this functionality (I'm not a VB6 developer, so I'm not familiar with the features they provide).  These features can also be provided at runtime via handling of the various form events (On Open, On Load, etc.).

**Additional context**
I'm not convinced this is a good idea.  Would this be like putting out X-Acto knives and Krazy Glue for a pre-school arts and crafts project?  It could be a useful shortcut or it might encourage the creation of hopelessly unmaintainable applications.  This feels like the long-running argument over whether to allow variables in CSS.

I think it's an interesting enough idea that it's at least worth discussing with the community.

**Comment by WaynePhillipsEA** [comment]
I think a really neat way of accomplishing this is to allow for control inheritance.  So instead of adding a standard 'CommandButton' to your form, you'd add MikesCommandButton, which has the default values customized to your pleasing, in the constructor of MikesCommandButton.

**Comment by mwolfe02** [comment]
Yes, I like the idea of control inheritance much better.  More powerful _and_ cleaner.  It's probably less discoverable to a new user, but I see that as a feature and not a bug.  Keep the X-Acto knives and Krazy Glue in the top cabinet, as it were.

**Comment by bclothier** [comment]
*busts out the ol' soapbox* 

Ahem, I have some π to add to the onions to form opinions. 😄 

To be honest, I've never found a UI framework that can:

* is intuitive and easy to understand
* allows you to easily enforce a standard
* minimize the plumbing work, especially for templates or custom controls
* separate the code from presentation well

This comes down to the old engineering joke --- cheap, fast, reliable; pick 2. 

**Group 1: VBx /Access / WinForm (absolute positioning)**

I'm lumping all UX framework in one category because they are basically the same at the high level. They all are easy to get started and use. The event-driven model makes it very easy to understand and reason about. 

But they all suffer the same drawback that they can't enforce a consistent appearance -- colors, fonts and sizes are basically hard-coded and there's no style to manage it (you could argue Access' theme tries to help out but it's inadequate and half-baked). 

Because they all are absolute-positioned, changing layout is quite painful in comparison to other UI framework (see below for contrast). Inserting a new control in middle of an existing layout tend to be tedious and one can get sucked into a time trap of trying to get everything pixel-perfect. It's unfortunate that we are not paid by numbers of pixels nudged, so that is another ding.

But by far the biggest ding is the utter inability to create and use templates / user controls and have it be centrally managed by a single template. I think VB6 probably comes out the ahead in the group as it does offer ActiveX controls so there is more encapsulation compared to MSForms' Userform or Access' forms/controls. However, creating an ActiveX control just to create a custom control for internal use seems a bit overkill. 

**Group 2: HTML & CSS & JS / XAML & WPF (flowing markup)**

In contrast, we have UX framework based on a markup language. The biggest advantage of a markup language is that you can effectively separate the presentation from the logic. Furthermore with CSS, you can easily enforce a uniform look & feel without having to code it up for each control added. Thus, changing style is very easy and seamless. Want bigger fonts? No problemo. Everything will resize more or less seamlessly. Want dark theme? Done. Much easier than the previous group.

When you need to add a new control; everything will flow out so for an experienced developer, it's very easy to make changes like that compared to controls positioned using absolute coordinates. But for a newcomer, it can be hair-tearing experience because they get caught up in 1000s little "gotcha!" where the flowing doesn't work as expected. 

Because the code is separate, it is very easy to define behaviors and apply it to certain class of controls which means lower coupling and more reusability but at expense of having more layers in between. Again, for a newcomer that can be daunting when the [law of leaky abstraction](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/) works against the newcomer (*"why won't this control show the date picker when I've obviously told it to?!?"*). 

Despite that shortcoming, it does makes it much easier to customize and re-use the customization without falling into the trap of endless tweaking for 107th variant.

Similarly, we avoid coupling properties to certain controls. A button could have a `HoverColor` property but a textbox doesn't. Why? Who say a textbox can't change color when it's hovered over? XAML does a great job here in making it possible to define styles uniformly across a set of widely disparate controls.

**Can we do better?**

I'd like to hope so. I've identified the major problems with both paradigms. I think one thing that is consistently missing in any UI paradigm is the ability to start out simple but still have the option to pop open the hood and start tweaking and a uniform system of references that can be statically analyzed. 

In the specific matter of absolute positioning vs. flowing, I've found Access' layout grids to provide a great way to balance the two with some additional polishing. In the specific matter of colors & fonts & visual styles, a system to map all the usages and associate styles & behaviors is necessary. The code behind the forms should be minimal and deal only with the data, rather than both data and behaviors. The WinForm group is too coupled but the XAML group makes it too hard to connect the dots & visualize the flow.

For additional considerations, I highly recommend reading the ducky's [discussion on "smart UI" anti-pattern](https://rubberduckvba.wordpress.com/2017/10/25/userform1-show/) and the early attempt to develop [MVVM in VBA](https://rubberduckvba.wordpress.com/2020/09/13/model-view-viewmodel/).

**Comment by uwbwsvd** [comment]
I'm a MS-Access-VBA developer and I did a look at XAML and I must say I like it. Thats all. My attemps never ended up in a usefull application. If something like XAML would be possible in a new VB, I think in would be nice.

**Comment by YogiYang** [comment]
The ideas proposed here is just outstanding!

Can we implement a new type of form called Web Form in TB? 

Here the UI will have to be defined using controls offered by HTML.

**Comment by WaynePhillipsEA** [comment]
@YogiYang Yes, web forms are planned once the web-server extension goes live, and the form-designer I'm creating now will be re-used for it.

**Comment by YogiYang** [comment]
I saw the teaser video of upcoming Form Designer. It is coming up great but I have one suggestion to make.

Please check out b4x.com's IDE implemented in all their products. If you implement such an IDE in TB would be easier and faster.

**Comment by bclothier** [comment]
I just read the last few comments and I want to strongly warn against reinventing the old ASP.NET WebForms.  That was a disaster and should not be repeated. It’s also a huge lie because it tries to present the web form as if it was just another rich client event-driven forms when in actuality, it was bloated html page demanding full postbacks for everything and constantly pushing state over a _stateless_ protocol.

I’m strongly of the opinion that the presentation layer and logic layer must be separate in a web view, something that almost never happen in a VB6 or Access forms where the “Smart UI” antipattern abound.

For the best experience, it may be necessary to allow JavaScript to handle the presentation which is admittedly suboptimal (I would rather code in C than in JS....) but that’s the only way to build decent, responsive and robust web applications.

**Comment by WaynePhillipsEA** [comment]
@bclothier don't worry, that's not what I had planned.   Think more along the lines of being able to compile tB procedures down to WebAssembly... (a subset of the syntax at least).  But that is way further down the line.

**Comment by WaynePhillipsEA** [comment]
Control inheritance is now a thing... https://github.com/WaynePhillipsEA/twinbasic/discussions/707

I'm thinking that control inheritance pretty much satisfies your requirements for this issue.  Would you agree @mwolfe02?

**Comment by mwolfe02** [comment]
100%.  Control inheritance meets the goals of my request in a much cleaner form than anything I had in mind.
