### ISSUE TITLE
Option Private Module not supported

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#29]
**Describe the bug**
In a module, one can specify `Option Private Module` which then prevents the module from being shared outside the VB project. 

In twinBASIC, that option is not recognized.

**To Reproduce**
1. Create a module `Module1`:
```
Module Foo
    Option Private Module
End Module
```
2. VSC will mark the `Private Module` as a problem with message: `syntax error.  no handler for this symbol`

**Expected behavior**
It should be supported. One particular concern is that this is theoretically possible:

```
Module Foo
    Attribute VB_Exposed = True
    Option Private Module 
End Module
```

What does that mean? 😆 If the option directly affects the attribute, then probably shouldn't be legal. 

**Desktop (please complete the following information):**
 - OS: Windows
 - twinBASIC compiler version v0.9.1602

**Comment by WaynePhillipsEA** [comment]
Some overlap here with #11

At the moment, all modules are effectively private, since they don't appear in the type library (which is correct), and the only way of referencing them outside of twinBASIC would be from a second twinBASIC project, which isn't yet supported.

The attribute should be accepted though, ready for future.

**Comment by WaynePhillipsEA** [comment]
Now supported, as of v0.9.2220

**Comment by bclothier** [comment]
I want to clarify something. 

I understand that a `TKIND_MODULE` can contain a [DLL entry point](https://docs.microsoft.com/en-us/windows/win32/midl/entry). Looking at the type library for `VBE7.dll`, it seems to be the case for its various functions.

```
[
  dllname("VBE7.DLL"),
  uuid(39D67E60-2BCC-1069-82DB-00DD010EDFAA),
  helpcontext(0x000f6ec3)
]
module Math {
    [entry("(null)"), helpcontext(0x000f64d2)]
    VARIANT _stdcall Abs([in] VARIANT* Number);
...
};
```

I assume in this case, the type library for VBE7.DLL is telling that it can find the entry points for functions defined in the same DLL file somehow? Can tB do the same?

**Comment by WaynePhillipsEA** [comment]
@bclothier please see my proposal for exporting DLL entries:
https://github.com/WaynePhillipsEA/twinbasic/issues/22#issuecomment-821348547

For COM/ActiveX projects, functions defined in my proposed DllExport block would indeed be output to the type library.  Note that VB6 doesn't offer such capability, hence the need for the DllExport modifier.  We could (should?) wait for attributes support (#25) instead of adding a new modifier though...
