### ISSUE TITLE
Dragdrop into text editor does not work as expected

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#290]
**Describe the bug**
DragDropping a file into the text editor clears existing text and displays the new dropped text (but without syntax highlighting) but this is only transient, any activity and new text lost, old text restored.

**To Reproduce**
1. F1 add a new class to project (either.CLS or .Twin)
2. Drag a file into the newly displayed text editor (any ascii file such as a  VB.CLS or a .TXT)
3. Original contents lost, new text shown without syntax highlighting.
4. Click on something else in the project tree such as settings.
5. Return to the module
6. New text has gone, original text restored. 

**Expected behavior**
The new dropped file contents should be inserted at the current cursor position.
If this is not possible then dragdrop should be disabled.

OS: Windows 10
twinBASIC  0.10.3429

**Additional context**
This would be very useful functionality if including several VB classes into a is a single Twin module, quicker than a copy and paste..

**Comment by WaynePhillipsEA** [comment]
Unfortunately I don't think VS code gives us any control or notifications (...or anything) for drag/drop operations.  I agree though, it would be handy to be able to drop multiple CLS/BAS files into a twin file and have it automatically wrap into Class/Module blocks.

I'll get the semantic highlighting and the revertted file data fixed though.

**Comment by WaynePhillipsEA** [comment]
So what's actually happening here is that when you drop a file into the code editor area, VS Code simply opens that external file for editing.    The file previously being edited is not touched (and you'll see the tab still there for it).

Since external files are not part of the twinBASIC project workspace,  the compiler doesn't know about the dropped file and so can't provide semantic highlighting etc.

In v0.10.3482 I've added a notification to indicate that the file that got dropped is an external file.  This is temporary, as I actually want to provide an inline message in the text editor to the same effect, and with an 'import' option, but I need to implement the codeLens feature in the language server first in order to offer that.  I'll leave this issue open until the preferred behaviour is in place.

**Comment by WaynePhillipsEA** [comment]
With the inclusion of CodeLens support (#299), you'll now see this warning message in v0.10.3511:

<img width="471" alt="codeLens2" src="https://user-images.githubusercontent.com/25738109/127112456-89fbfc76-6bc0-4677-8c29-d3f776bea876.png">
