### ISSUE TITLE
Many errors (problems) in big Class

### ISSUE THREAD

**Issue by dmrvb** [WaynePhillipsEA/twinbasic#319]
**Describe the bug**
I have a Big class,  4000+ lines and lots of methods. TwinBASIC is reporting over 1000 problems.

I can not identify a code error as the source of these problems. It feels like TB gets most way through the code then just sort of gives up. It starts failing to recognise sub definitions, not understanding IF's and reporting ambiguous variables even though they are local to each sub

Shall I send you the code?  If possible I would prefer not to make it public.

.
 - OS:  Windows 10
 - twinBASIC compiler version: several including 3697

**Additional context**
I have spent a fair bit of time on this and got nowhere.

**Comment by WaynePhillipsEA** [comment]
Yep, I'd certainly like to look at that for you.  Could you possibly upload the twinproj file here as a ZIP with a password, and then send the password separately to wayne@t..b..com (obscured to prevent spam)  or DM me on Twitter if you're on there.

**Comment by dmrvb** [comment]
[GDIFFTtestTB.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6926987/GDIFFTtestTB.zip)

Project enclosed, no password as have removed any sensitive information.
I see 1000+ problems, hope you do to.

I have quite a few big classes like this, that's my programming style, and this is why I would love a tB option to display just the current sub/function in the edit window.

**Comment by WaynePhillipsEA** [comment]
Thanks for that.  There is only 1 line that tB is struggling with:

> If nband > oFFTlines Then: OctEndBand = octband - 2: Exit For 'run out of narrowband so set endband

If you split that up or comment it out, your 1001 errors come down to 12.  Those 12 remaining issues are legitimate unrecognized symbols.

Due to the problem parsing the line, tB is seeing it as an If block without a closing End If.  That then causes knock-on errors for ALL remaining code, since End Sub/Function/whatever won't be considered inside an open If block.  The supplementary fix here needs to be that End Sub/Function/etc need to be interpreted even when there are open If/Do/etc blocks, for parser recovery purposes.  That way, the knock-on effects are limited to only the current procedure rather than the full remaining document.

**Comment by WaynePhillipsEA** [comment]
The single line if bug is fixed in v0.10.3900, thanks for reporting and sharing the code.   The parser recovery as discussed above is also improved in this release.

**Comment by wqweto** [comment]
Nice!

A single-line form `If` statement with several statements on the logical line is a nice edge-case that I've personally never seen/used in production.

Btw, single-line form allows `Else` part with multiple *elsestatements* too but no `ElseIf` is allowed for no apparent reason.

It was expected more of these to come pouring once people believe in TB and the porting of existing projects takes off.

**Comment by WaynePhillipsEA** [comment]
Yup, tB was actually handling this correctly except for the immediate line splitter following the Then

**Comment by dmrvb** [comment]
Thanks, I thought it was something like that but I couldn't spot it.
I try not to use single line IFs too much but sometimes they are neat and useful.
I have a few code sections dating back to 1985 GWBASIC and a fair bit translated from Fortran.
