### ISSUE TITLE
Control+Y shortcut support

### ISSUE THREAD

**Issue by EduardoVB** [WaynePhillipsEA/twinbasic#321]
**Is your feature request related to a problem? Please describe.**
Keyboard shortcut Control+Y not currently supported in tB (version 0.10.3790)

**Describe the solution you'd like**
In the VB6 IDE, Control+Y deletes the current line (regardless it is selected or not) and puts it into the clipboard.
It is very handy.

**Comment by WaynePhillipsEA** [comment]
After all these years, how did I not know of this shortcut?! ...

The problem with this is that most text editors these days use Ctrl+Y for 'redo' (after Ctrl+Z 'undo'), and as such this is the default behaviour in VS Code.

What I can do though is provide a VS Code command to do the same thing, and then you'll be able to assign that command to any shortcut through your VS Code Preferences > Keyboard Shortcuts.

**Comment by WaynePhillipsEA** [comment]
I've just realised that normal 'Cut' in VS Code (Ctrl+X) cuts the whole line when there is no range selected, so that is effectively the same as VB6's Ctrl+Y (except for when a range is selected).  

So to assign this behaviour to Ctrl+Y, follow these instructions;

Open VS Code > File menu > Preferences > Keyboard Shortcuts
Search for clipboardCutAction
Right click on one of the entries > Add keybinding...
press the keys Ctrl and Y together, followed by Enter

You should now see the new keybinding listed, and hopefully it should start working in code editing.

**Comment by EduardoVB** [comment]
It worked, thank you.

> After all of these years, how did I not know of this shortcut?!

I guess it was not properly "advertised". I discovered it at some point years ago. I guess the people that knows about it use it a lot, because it is very handy for moving lines (one line at a time) to another place.
