### ISSUE TITLE
Enumeration cannot be renamed

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#330]
**Describe the bug**
the twinBasic editor is unable to rename the name of an enumeration

**To Reproduce**
```
Public Enum Orientation
```

cannot be renamed to 

```
Public Enum KeysOrientation
```
using the command 'Rename symbol'

This issue may just be a marker for a preview limitation

**Comment by WaynePhillipsEA** [comment]
Sorry, I can't seem to reproduce this problem.

**Comment by FullValueRider** [comment]
The error reported is "Rename failed to apply edits"

The  Code in which this enumeration is used are new additions to  my twinbasic version of VBALib. The new files were drag and dropped into twin basic as bas and cls files. the Kvp related files are being heavily refactored and were moved in to  twinbasic  to allow more convenient editing due being able to have multiple views of the same file.

The updated VBALib is attached

The enumeration is declared in the KvpAid.bas module.

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6944653/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks, I was able to repro in your project.

**Comment by WaynePhillipsEA** [comment]
Fixed in v0.10.3985, thanks for reporting.

Just FYI, one of the references to the Orientation enum is from a parameter default value in Kvp.twin, and it is a known issue that default values are not yet included in the rename refactoring, so this rename operation will require that one to be updated manually for now.
