### ISSUE TITLE
Missing line labels are not escalating to compilation errors

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#332]
**Describe the bug**
I'm seeing an unexpected compilation error reported when I try to run a particular method.  There are no errors flagged in twinbasic and the code works as expected in the VBA ide.

The method is
```
Public Sub Test15_CopyToItem2ToEnd()
```
In module Main.twin

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6944802/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting, I'll look into it later.

<img width="290" alt="tb_InternalError" src="https://user-images.githubusercontent.com/25738109/128496752-334d3b08-d660-4088-bc8c-c9df4cd882a0.png">

Just FYI, when you get a compilation error like that at runtime execution, it indicates a code-generation error which is the final stage of compilation.  You can read that as 'internal error' if you like, since all verification passed and twinBASIC accepted your code... it's purely a tB problem at that point.

**Comment by WaynePhillipsEA** [comment]
So actually this is a legitimate error in your code, but twinBASIC is not validating and reporting it properly.

You're missing a line label for TestExit in 'Test15_CopyToItem2ToEnd'.

Let's leave this issue open until the error gets reported more appropriately in VS Code.

**Comment by WaynePhillipsEA** [comment]
Fixed in 0.10.3985, thanks for reporting
<img width="219" alt="tb_lineLabelVerification" src="https://user-images.githubusercontent.com/25738109/128589855-522a51c3-9461-4d0d-8513-eb71d5d55a47.png">
