### ISSUE TITLE
VS Code AutoSave conflicts with prettifier

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#333]
Intellisense is making an incorrect substition

The error is demonstrated when attempting to type 

```
If Types.Arrays
```
in a case structure

**To Reproduce**
Goto method
```
Public Sub pvAddOrInsertTableArray(ByVal ipTable As Variant, ByVal ipOrientation As Orientation, ByVal ipStartIndex As Long)
```
Try typing the above 'If' text for the first case condition
```
        Dim myLyst As Lyst
        Select Case ipOrientation
            
            Case Orientation.CopyCol1
            
                IfTypes
```
The space types between if and Types is removed.
When the dot is added the substitution to 
```
ClassInterfaceType_AutoDispatch.
```
occurs

This problem is intermittent.  I haven't found a keystroke sequence that reliably reproduces the incorrect substitution, but this error, and others similar to it are happening on a reasonably frequent basis.

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6945357/VBALib.zip)

**Comment by WaynePhillipsEA** [comment]
Have you got the VS Code 'AutoSave' feature on by chance?  Try turning it off and see if that helps.

**Comment by FullValueRider** [comment]
Thanks for the hint.  Autosave is set to "AfterDelay".  I've switched it to "Off" for now and will report back if I see further issues.

**Comment by WaynePhillipsEA** [comment]
ClassInterfaceType_AutoDispatch is a legimiate match for 'IfTypes', due to the camelCase matching that VS code does in intellisense.

The problem here is only the space being removed between the 'If' and 'Types', which can occur if the prettifier kicks in, removing trailing line spaces before you've type the 'Types' part.  That bug should only happen, as far as I'm aware, if you've got the AutoSave feature ON which causes the prettifier to kick in too early after a set time (usually 1-second).

**Comment by WaynePhillipsEA** [comment]
As of v0.10.3965, the AutoSave feature of VS Code should no longer interfere with the twinBASIC prettifier.
