### ISSUE TITLE
InputBox improvements

### ISSUE THREAD

**Issue by DaveInCaz** [WaynePhillipsEA/twinbasic#349]
**Is your feature request related to a problem? Please describe.**
It is <strike>impossible</strike> [non-intuitive and hacky ](https://stackoverflow.com/a/3123730/3195477) to distinguish between the user entering a blank vs. pressing Cancel when using the VB6 `InputBox()` function. I assume VBA was similar (?). 

**Describe the solution you'd like**
Add a variant of the `InputBox()` function which can distinguish the two cases.

The VB6 function is like this:
![image](https://user-images.githubusercontent.com/18285074/129232646-eae4583c-1e81-405b-b979-e0361e77baed.png)

Maybe an additional 'overload' of that function which returns boolean (or an enum?) for OK/Cancel + a ByRef for the user's input value.  This would follow a fairly common pattern.

**Describe alternatives you've considered**

One could obviously code a wrapper or their own form, but InputBox is so useful despite being so simplistic that this doesn't seem ideal. 

**Additional context**
FWIW this behavior was (properly) copied into the .NET equivalent `Microsoft.VisualBasic.Interaction.InputBox` I assume because they were going for backwards compatibility.

**Comment by WaynePhillipsEA** [comment]
The way this is traditionally done in VBx is to check the returned string pointer with StrPtr().  If the pointer is zero, then cancel was pressed.  This also works in tB.

It is quite cryptic though, so I'm open to suggestions. 
 Perhaps we could offer object/class based alternatives for dialogs.

**Comment by Kr00l** [comment]
IMO object/class based dialog is an overkill for just that. Only if tB plans to add more. (?)

In excel the Application.InputBox returns a variant.

The most elegant way would be InputBox As Variant and InputBox$ As String.
However, due to backwards compatibility this is not possible.

So my opinion is to keep it like it is. If another way is desired whatsoever then maybe an alternative InputBoxV ?
So one could check:
```
Dim Result As Variant
Result = InputBoxV("Test")
If IsEmpty(Result) Then
  MsgBox "Cancel pressed"
Else
  MsgBox "Text is:" & Result
End If
```

**Comment by WaynePhillipsEA** [comment]
Another option would be to throw an error if the dialog is cancelled.  Only when we set a new optional argument 'CancelThrows' or something like that.

**Comment by Kr00l** [comment]
> Another option would be to throw an error if the dialog is cancelled. Only when we set a new optional argument 'CancelThrows' or something like that.

Also good idea. In the CommonDialog world this is a property and is named 'CancelError' As Boolean.
I like that wording. :)

**Comment by wqweto** [comment]
Using exceptions for flow-control is always a clumsy idea. It ruins Break on All Errors setting too (which is a zen experience in itself:))

**Comment by dmrvb** [comment]
I'm with wqweto on this, too many "routine errors" can be a right pain.

inputbox returns an empty string on cancel, surely that's good enough???.
otherwise could have an optional argument "cancelled as boolean"

and on the error subject, how about an option to turn off errors in the file system, "Open" in particular, and return an error code instead????.

**Comment by Kr00l** [comment]
> I'm with wqweto on this, too many "routine errors" can be a right pain.
> 
> inputbox returns an empty string on cancel, surely that's good enough???.
> otherwise could have an optional argument "cancelled as boolean"
> 
> and on the error subject, how about an option to turn off errors in the file system, "Open" in particular, and return an error code instead????.

I also think a null string is good enough. But if really wanted I like this "Optional ByRef Canceled As Boolean" (1 L = American English, 2 LL = British English) more than an error exception.
Or again, just let it be like it is now.

**Comment by WaynePhillipsEA** [comment]
I dislike introducing an out-flag parameter since there's no prior use of that design pattern throughout the built-in VB libraries, as far as I can remember.

Since there's no agreement, we'll leave it as it is for now.  I suspect we'll add a customizable dialog class at some point, and that would then be the time to implement such a change.

**Comment by dmrvb** [comment]
I've done my own msgbox and inputboxes (and file system) so will be very happy to share ideas at some stage in the future.

**Comment by Kr00l** [comment]
I found a mismatch.
In VBx the max length of text (EM_LIMITTEXT) is 254.
tB has no limit which might be a compatibility break.

**Comment by EduardoVB** [comment]
I have an idea, and it is to introduce an optional parameter that would be an input flag that when set to true the return value will be **a null character** in case the dialog was canceled.
That wouldn't break backward compatibility and allow an easy way to check for cancellation without any output parameter..

**Comment by bclothier** [comment]
FWIW, I would argue against enchancing the classical `MsgBox` and `InputBox` *functions* because as noted earlier, there are no agreements and a huge amount of conflicting requirements. IMHO, those functions are an antipattern and never should have existed. 

It would be better for tB to provide templates that is easy to customize and extend to accommodate different requirements and have a uniform design experience than to shoehorn into the poorly designed functions.

FWIW, in my applications, I elected to shadow the `MsgBox` as to reroute into my custom dialogs as to get uniform appearance even for inherited code that still use those functions. tB certainly could do the same.

**Comment by Kr00l** [comment]
I also argue to not change or "improve" MsgBox or InputBox and just have them for compatibility.

Regarding compatibility the only thing missing for InputBox is IMO a EM_LIMITTEXT set to 254. Currently it's w/o limit.
