### ISSUE TITLE
Me symbol can be passed ByRef

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#4]
**Describe the bug**
twinBASIC does not currently allow the Me instance to be passed to a ByRef parameter, giving error 'unable to bind to reference; this is a read-only binder'

**To Reproduce**
1. Create a class
2. In the constructor (or any defined member procedure), call another procedure, passing the Me instance variable as a ByRef argument

**Expected behavior**
The compiler should allow this behaviour.

**Desktop (please complete the following information):**
 - Windows 10
 - twinBASIC compiler version 0.9.1602

**Additional context**
Even though the Me instance variable is not set-able, VB allows it to be passed ByRef, wrapped in a temporary variable. 

**Source**
vbforums [wqweto]

**Comment by retailcoder** [comment]
This seems related (or should it be a separate issue?), but it looks like a possible overload resolution issue involving interfaces implemented by `Me`... when it's passed *by value*:

![unable to disambiguate between two constructors](https://user-images.githubusercontent.com/5751684/114816562-6031ff80-9d86-11eb-9fd6-5045c6effda4.png)

Changing the call site to declare a local `Dim instance As IPropertyBinding = Me` and pass `instance` instead of `Me` fixes the problem, but twinBASIC should have enough metadata about `Me` to resolve the correct constructor overload here.

**Comment by WaynePhillipsEA** [comment]
I don't think that is related actually.  But it is definitely a bug that needs to be fixed.

**Comment by WaynePhillipsEA** [comment]
Both fixed in v0.9.1750, thanks for reporting.
