### ISSUE TITLE
#Error keyword for conditional compilation

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#404]
**Is your feature request related to a problem? Please describe.**
In VBx and tB it is not possible to block a compilation of an "unwanted" conditional compilation scenario.

**Describe the solution you'd like**
To introduce new conditional keyword `#Error` that will block compilation.
Example would be:
```
#Const CustomerNumber = 37
#If CustomerNumber = 35 Then
        ' Insert code to be compiled for customer # 35.
#ElseIf CustomerNumber = 36 Then
        ' Insert code to be compiled for customer # 36.
#Else
        #Error ' Unknown customer, can't compile.
#End If
```

**Describe alternatives you've considered**
n/a

**Additional context**
Possibly allow to pass an error message to `#Error` that tB will then show up.
On above example the comment could be changed to a string.
`#Error "Unknown customer, can't compile."`

**Comment by DaveInCaz** [comment]
I also use this type of conditional compilation to produce variants of a program and I'd say the ability to error-check at compile time would be very useful.

The string arg to `#Error` is very important, would help locate the problem more easily than a line # or whatever else the compiler might output.

**Comment by wqweto** [comment]
You can put the error message without #Error and without quotes and it will bomb out if this branch ever gets compiled by mistake. That’s what I do at least in VB6 i.e. invalid code in non-compiled branches is fine (at least until it’s compiled).

**Comment by bclothier** [comment]
FWIW, I'd rather not extend the magic `#xxx` syntax beyond backward compatibilities. There are better approaches. [I outlined one in another issue](https://github.com/WaynePhillipsEA/twinbasic/issues/25#issuecomment-821741827) where we can use attributes which would mean instead of having both live and dead code in codebase which can be very bad for analysis, we can have it be always validated and optimized out when not used, which gives us the best of both worlds.

**Comment by Kr00l** [comment]
In C# the following error and information directives exist:

```
#error: Generate a compiler error with a specified message.
#warning: Generate a compiler warning, with a specific message.
#line: Change the line number printed with compiler messages.
```

**Comment by bclothier** [comment]
TBH I've never seen those used in the wild. `#line` sounds particularly horrid to me; it sounds like this would be a huge maintenance traps in making. This is far more easier to maintain:

```
[Warning("This method requires use of XML library called in the {nameof(GenerateXMLDocument)} procedure"]
Public Sub Foo()
...
End Sub
``` 

Note that because the `Warning` attribute is code, we can use expressions such as `nameof()` to reference a procedure that exists somewhere in the module. This is also friendly for refactoring since renaming a procedure name ensure that this will be updated. That avoids having stuff like `"This procedure requires use of XML library in procedure MakeXML on line 122"`, only to find that there's no procedure named `MakeXML` and it's not even on the line 122. Surely you've seen many error messages that contains outdated data because people forgot to update details like those. 

For that reason, I really don't want to use the preprocessor syntax -- they cannot be parsed just like code and being able to refactor is very important in attracting new people to the language, IMO.

**Comment by Kr00l** [comment]
> You can put the error message without #Error and without quotes and it will bomb out if this branch ever gets compiled by mistake. That’s what I do at least in VB6 i.e. invalid code in non-compiled branches is fine (at least until it’s compiled).

Didn't think of that.
Of course the #Error thing looks/feels more professional but in case it will not be incorporated  it's a good workaround. :>

**Comment by wqweto** [comment]
Btw, #line is super handy for generated code e.g. generating parser class from PEG grammar with lines from the source .peg file.

I’m very much pro C/C++ preprocessor incl. #define directive for macros although this will slow compile time considerably so probably should remain outside scope of TB.

**Comment by WaynePhillipsEA** [comment]
It would be really simple to add support for #Error and #Warning... but I appreciate the arguments raised by @bclothier against it.  I'll leave this discussion open for now to see if any other views come in before making a decision on it.

**Comment by Kr00l** [comment]
I don't know how #Warning would be visualized in VS code. If it is just an information message then #Print would be more appropiate than #Warning IMO.
#Print is also used in FreeBasic, for comparison (also #Error and #Line). Just for information.

**Comment by mansellan** [comment]
I quite like the preprocessor directives tbh. I take @bclothier 's point about attributes being "better", but I think this is a case where it's justifiable to have both. There's prior art for that in VB.Net, and it brings it into line with FreeBasic too (which I'm finding quite inspirational having not seen it until recently).

**Comment by WaynePhillipsEA** [comment]
Given the prior-art in other languages, plus with people using less formal alternatives (https://github.com/WaynePhillipsEA/twinbasic/issues/404#issuecomment-912676883) I figured this feature is worthy of inclusion.  

Support for #Error and #Warning directives are now included, as of v0.10.5450

<img width="720" alt="tb_ErrorDirective" src="https://user-images.githubusercontent.com/25738109/132117969-63c24e06-4c9e-4ced-9e0c-c6d97ad1be53.png">

Also added compiler warning id TB0005 to support the custom warning, and to allow to turn the warnings off in the project settings.

**Comment by Kr00l** [comment]
Setting TB0005 to IGNORE seems not to work.

Also setting TB0005 to ERROR (to turn a #Warning into an #Error via setting) seems not to work.

**Comment by WaynePhillipsEA** [comment]
@Kr00l thanks, fixed in v0.10.5452.   The settings were working correctly inside component-scope but not in global-scope.

**Comment by bclothier** [comment]
Adding comments for further considerations in regard to language design:

While prior art in VB.NET and FreeBasic makes for a good argument, it is worthwhile to consider whether it will actually hinder the maintenance. The more options there are, the more complicated it becomes to maintain the codebase and in my mind, refactorability is very important for success of the project --- if you can't refactor the code cleanly and safely, then the payment of technical debt can become prohibitively expensive. 

For that reason, it's worthwhile to look at what other languages are doing (or in this case, _not_ doing). Take Rust for example --- it's basically meant be used in systems programming --- an area where C/C++ dominates. It has no preprocessor. [This section may be relevant](https://docs.rust-embedded.org/book/c-tips/index.html).

Then there's TypeScript which has a closed issue that has discussed the pros and cons of preprocessing, but [ultimately didn't go for it](https://github.com/Microsoft/TypeScript/issues/4691). 

To provide a more concrete example of where preprocessing can hinder maintenance, consider the trick I usually use to support early & late-binding, something I call "two-headed procedure":

```
#If LateBind Then
Public Function ExcelApp() As Object
#Else 
Public Function ExcelApp() As Excel.Application
#End If 
  Set ExcelApp = CreateObject("Excel.Application")
End If
```

Currently, the codebase would only see only one branch at a time. Therefore if I were to do a rename refactor, and change from `ExcelApp` to `GetExcelApp`, it would end up in an inconsistent state unless the refactors were able to look into preprocessor's grammar, but at that point, that becomes too much of a mind-reading exercise and could actually create problems. For that reason, I'm now regretting my "clever" trick of using two-headed procedure since that is now a trap - yes it allows me to have best of both world (convenience of development with early-bound libraries and reliable deployment that won't break due to versioning) but with a codebase that I can't refactor easily. 

Anyway, wanted to share that for the future language design considerations. :)

**Comment by wqweto** [comment]
I’ve used two-headed declares only to modify routine scope (public vs friend) as UDTs were used on public interface and in Std-EXE these cannot be public etc. compiler brain fa*ts.

Using preprocessor in my case would be able to define scope and use `MyScope Sub MyRoute(…)` instead and get rid of any two-headedness.

In yout case even a preprocessor is an overkill as you wiuld be able to use a typedef to alias the retval type if TB delivers the feature.
