### ISSUE TITLE
Restructiring to remove Inconsitencies and boilerplate associated with parameterised constructors

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#46]
Firstly, let me say that I love the parameterised constructors in twinBasic but having played with them a little there are some niggles due to inconsistencies and boilerplate.

**Is your feature request related to a problem? Please describe.**

Inconsistency 1:  The New constructors may be declared as a sub or a function. 
Inconsistency 2:  The method is New but the instantiation is via New Obj rather than Obj.New. Writing obj.New gives a compiler error.

Boilerplate: It appears to be mandatory to have a parameterless new declaration in addition to any parameterised constructors.  Omitting this parameterless declaration gets the whole class flagged as a compiler error.

**Describe the solution you'd like**
1. Elimination of boilerplate
2. Improved consistency with existing method calls

1. The New method should be a function (and possibly require the return type to be stated explicitly rather than as an implied variant)
2. The instantiation of an object should be via Obj.new
3. New to be allowed as the default Member and that this attribute, if used,  applies to all constructors in a class (This aspect could possibly extended to cover a group of overloaded methods)
4. The elimination of the requirement for a parameterless New() constructor.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
Thanks for highlighting some issues here.   New() constructors should NOT be allowed to return values, so they should always be Sub, not Function.  The compiler will enforce this in tomorrows update.

I don't agree that instantiation of an object should be via Obj.New().   The New operator is how VB6 and VBA developers will expect objects to be created.

Public classes are COM visible, and COM does not support parameterized constructors, so the compiler would ordinarily create an implicit parameterless constructor for you.  However, because you have defined parameterized constructors, there is assumed intent that you want the class to be constructed with arguments, and so the compiler won't automatically generate a parameterless constructor for you, and expects you to provide one.   

If you don't want that behaviour, consider if you really want the class to be COM-visible.  If you don't, you can add 'Attribute VB_Exposed = False' immediately underneath the Class statement, and then the compiler doesn't need the parameterless constructor.  Soon you'll be able to specify Private Class instead of the VB_Exposed attribute... See #11

**Comment by FullValueRider** [comment]
Thanks for the quick response.   I think you are wrong on all counts, but as its your compiler its up to you as to how you want to run things.  I look forward to when the Predeclared Attribute becomes available so I can use my parameterised  self factory classes in the same way as I do under VBA.

**Comment by retailcoder** [comment]
1. Wayne is not wrong at all.
2. Learn how constructors work in other languages like VB.NET, Java, C#, and many others, before you dictate how they are supposed to work in this one. Constructors are NOT like member methods.
3. Constructors make VBA-like factory methods off default instances *completely redundant*, and I definitely need to write about how and why that is the case. You need these factories in VBA to *simulate* having a parameterized constructor.
4. Parameterized construction also removes the need for many explicit interfaces, and having access to the object's internal state means you directly assign the fields and no longer need `Property Set` members to property-inject dependencies. Instead we can now do what everyone else does in every other language: *constructor injection*, and everything becomes massively simpler all of a sudden.

**Comment by bclothier** [comment]
FWIW, I was a little surprised to see that VB.NET does this:

```
Public Class MyClass
  Public Sub New()
  End Sub
End Class
```

IMO, it should have followed C#'s lead:
```
Public Class MyClass
  Public New()
  End New
End Class
```

Why? Because constructors and destructors shouldn't be called as if they are just another member methods. Furthermore, the inheritance/chaining of constructors in .NET works differently. If tB has any plan for handling the chaining of constructors, the compiler should prevent anyone from trying to call the constructor directly. That shouldn't be legal. Using `New` in place of `Sub` or `Function` help emphasize that point, or at least I thought that was why C# did that way. 

I should also point out that though we do abuse the predeclared attribute to get "static" methods, they are in fact still member methods and requires an instance, unlike C#'s `static` / VB.NET's `Shared` methods. Because COM works with interfaces, we cannot directly expose such methods. Therefore, the most natural solution for handling construction of an object is to create a factory class/module as a separate object and make it call the parameterized constructor. There's a potential for tB to autogenerate factories to fill the parametrized constructors and thus make it useful for external COM clients.

**Comment by WaynePhillipsEA** [comment]
@bclothier I like that idea.  Would you have it as a single predeclared class factory (per typelibrary) or individual ones, i.e one per class?   Might be worth opening another issue to discuss.

**Comment by WaynePhillipsEA** [comment]
We also need static (shared) class members.

**Comment by FullValueRider** [comment]
I'm sorry that my views have caused a negative response.  I'd be the first to acknowledge that I have no formal qualifications in any computing related subject, nor am I fortunate enough to have drifted into programming in my early days (back in the 80') have have learned from any mistakes I may have made.  

My views come from observing patterns and the cognitive dissonance that comes when the expected pattern is not fulfilled.  Based on my observations, in what I have read and from dabbling with a few programming languages, I've come to my understanding that some things we take as read (a la 'the Emperor's New clothes' ) do have a cognitive dissonance associated with them and as a consequence should be treated as being wrong, or perhaps more politely, incorrect embedded practises.  It is from this understanding that I get the views expressed above.  

I just wish I was clever enough to be able to write a compiler so that I could test opinions.

<sigh>

**Comment by retailcoder** [comment]
In VBA I personally like having a factory method in the class it's creating an instance of, for several reasons:

1. Calling `Thing.Create` off the default instance looks & feels *exactly right*.
2. It puts construction and dependency injection concerns where they belong, in the class module being instantiated.
3. It separates the class' default/stateless interface from its explicit/stateful interface; instance members are explicitly defined in an explicit interface.

In twinBASIC, with parameterized constructors *factory methods* are much less commonly needed, but *abstract factories* remain a valid and useful tool for dependency injection. The way I see it, the need for tB factory methods is rather limited, as much as it is in C# or VB.NET, because a factory method necessarily induces often-undesirable *coupling*.

Thus, if an *Extract Factory* refactoring tool is to be made, it should offer several options:
- *Extract Factory Method*: in a class with `VB_PredeclaredId` and `VB_Exposed` set to `True` and `VB_Creatable` set to `False`, adds a `Public Function Create` that copies the signature of the selected/current constructor overload, invokes it, and returns an explicit interface (prompt/select, I guess) if the class has `Implements` statements (extracts an interface otherwise?), or returns the class' default interface otherwise. Now that's... a lot of conditions and constraints I think.
- *Extract Factory*: creates a new `VB_Creatable` class with only the extracted `Create` method/function, parameterized as per a selected constructor overload. Returns the class' default interface.
- *Extract Abstract Factory*: in a class with `Implements` statements, creates a new `VB_Creatable = False` interface class with a `Create` method/function parameterized as per the selected constructor overload, and returns one of the interfaces implemented by the class. Optionally, the extracted factory interface could be automatically implemented by invoking the selected/wrapped constructor overload.

Factories are OOP stuff. Any "extract factory" tool that doesn't involve a class module should explicitly mention it:

- *Extract to Factory Module*: creates a new `Create{ClassName}` function in a standard module copying the signature of the selected constructor overload, returns the class' default interface.

I personally profoundly dislike the idea of having a God-like `AllTheFactories` module or class that can spawn an instance of just about anything from just about anywhere. While it should be *possible* to do it in tB, I don't think tB should be providing tooling to *facilitate* it.

**Comment by retailcoder** [comment]
@FullValueRider I apologize for the rather defensive tone of my reply, and to be completely honest `Sub New` *does* look rather weird.

The inconsistency comes from the fact that a constructor is invoked *as the object is being created*, whereas other members can only be invoked *after* the object is fully constructed.

So in VBA when you call `Thing.Create(42)` you're really dealing with 2 objects: one being the `Thing` predeclared instance that lets you make this member call in the first place, and then the factory-spawned instance. The 42 is *property-injected* through a `Property Let` member call against the `result` object that's being returned, and that `Property Let` member may or may not be defined in the interface returned by the factory method.

In twinBASIC when you call `New Thing(42)` you're only dealing with 1 object, the new `Thing` instance; the 42 is being *constructor-injected* here, so when the `New` operator yields the created object to the caller, the 42 is already part of the object's state and the object never even *exists* without that state initialized. This is very much fundamentally different than with VBA and property injection, where *the object is allowed to be first created in an invalid state*, and remains in this sort of limbo until the factory method returns the fully-initialized object.

This is why making `Sub New` a member call cannot make sense: because it's invoked *before* the object instance is usable by any code. As such, it *has* to look somewhat special and work differently than other procedure scopes in the class.

**Comment by FullValueRider** [comment]
@retailcoder  That's very generous of you.

Your explanation of why new is different is quite interesting.  

From my perspective the predeclaredid of VBA is identical to class code of objects in other languages.   VBA can do the magic trick of pretending that the predeclared code is a default instance precisely because it does not allow parameterised constructors.  However,  as you are aware, by the use of an anonymous new, VBA can be tricked into allowing a pair of functions that ultimately emulate what a constructor achieves.  

I see 'new Object' as implying that something outside of the object knows how to construct the object i.e. an invisible global factory. On the other hand, I see Object.New ( or better still object(parameter list)) as a much more honest and consistent statement.   

Its a little like Einstein's person in a box who is unable to distinguish difference between acceleration due to gravity or acceleration due to someone pushing the box.  The 'new' to declare a new object is an arbitrary and unnecessary complication as from a grammar perspective there  is no way to distinguish between Object(parameter list) and any other method that takes parameters and returns a value.  I'd also argue that from a program writing perspective there is actually no need to know.

I'm afraid this is where I am in my understanding.  I'm sorry if I am at odds with what is common practise and believe that common practise is mistaken.

**Comment by Greedquest** [comment]
Another take on this to think about: in python 3 the class definition is itself an instance of the `type` object. When you call the constructor of some class:
```python
instance = ClassName(1234)
```
what happens under the hood is a call to a class method followed by the instance method:
```python
clsType = type(ClassName) #no-op since ClassName is subclass of type
instance = clsType.__new__([cls=clsType], 1234)
    # make and return new instance of object defined by the ClassName type

instance.__init__([self=instance], 1234)
    # take the newly created instance and call its constructor
```
So in this example the class does just define a normal method (`__init__`) that gets the `self` instance pointer as a first argument to allow it to access private state and that's fine. For VB* this is just an Initialize Sub. What's important though is the `__new__` method is a static/class method so does not get an instance passed to it, but because it doesn't have the responsibility of doing the initialisation of the object, only creating it, it doesn't have to worry about the private state.

---

Bringing this back to tB, I guess the python style approach is that New with arguments is just parameterless New, followed by a call to a special Init method of the class that takes arguments for construction, but is otherwise a standard method. And then if you want to change the behaviour of the New operator (to allow constructor chaining for example), you need to define that as a static method of the class type rather than instance.

Not sure if that's clear, sorry typing on phone, and I've slightly simplified the workings, but that's the gist. So Newing up is operator overloading on a class level but construction and populating is a standard sub on an instance level.

**Comment by Greedquest** [comment]
For another perspective, here's how python (3) does it:

Broadly speaking the process is split in two - if I have a class called MyClass:
```python
instance = MyClass(1,2,3) # parameterised constructor

# roughly equiv to
instance = MyClass.__new__([cls=MyClass],1,2,3) # class creation method with first argument as type of class
instance.__init__([self=instance],1,2,3)        # instance constructor method with implicit self pointer
```

so in VBA this is really just 
```vba
Set instance = New MyClass(1,2,3)
'roughly equiv to

Set instance = New MyClass
instance.Class_Initialize 1,2,3
```

So New with arguments is just syntactic sugar for calling some init method of the class that does the constructing. Then you can introduce a `New` operator overload in tB which is a static/class method to let you do more fancy stuff like constructor chaining, but fundamentally just calls parameterless New then invokes init/Class_Initialise with args on the instance

**Comment by WaynePhillipsEA** [comment]
As of v0.9.1666, Function New() is explicitly disallowed.  Closing this issue.  If we're discussing a syntax change regarding Sub New, let's open a separate issue for that to be discussed.
