### ISSUE TITLE
Unable to find DLL entry point -  64bit DLL

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#503]
Running TB codes from within VSCODE produces an error  "unable to find DLL entry point".

When I compile to an EXE and the program runs fine.   (first 64bit exe !!!! )

I presume it may be down to where TB looks for the DLL I am using.  I put it into the same folder as the source?

**Comment by WaynePhillipsEA** [comment]
This will almost certainly be to do with how tB currently binds to DLL entries slightly differently than in VBx.  I think this problem is covered by #284 and #372, so I'll close this one.  I'll put this on this list to look at as soon as I've finished the file IO syntax support.    Great to hear that the 64-bit build worked for you 👌
