### ISSUE TITLE
Left("XXX", x) does not always work 

### ISSUE THREAD

**Issue by adakordev** [WaynePhillipsEA/twinbasic#511]
Create a fresh Sample 6 Project.
Paste following lines into this Sub "Private Sub NextButton_Click() Handles NextButton.Click"

  Dim tb As String = "twinBASIC"
  MsgBox Right(tb, 2)
  MsgBox Left(tb, 3)
  MsgBox Right(tb, 3) & Left(tb, 3)
  MsgBox Mid(tb, 2, 3)
![Left1](https://user-images.githubusercontent.com/31490758/143878675-f7adf22a-58d7-41db-a360-604799f6f421.JPG)

![grafik](https://user-images.githubusercontent.com/31490758/143879325-3c31462b-50fe-43f3-8224-ce939462e570.png)

Win10
0.13.8

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.   That's binding to the Form Left property instead of the Left function in the standard library.  You can prefix it with VBA (so `VBA.Left(tb, 3)`) to fix it for now as I'm not planning on touching the resolver for a couple of weeks.

**Comment by wqweto** [comment]
Just as a proposal, last time we discussed this edge-case which VBx parser resolves by explicitly binding `Left` with exactly two parameters to `VBA.Left` as a hardcoded exception I proposed to consider resolving *all* routines by matching on param count too.

I.e. on `Left(tb, 2)` the local scope will be searched for `Left` symbol for which a callsite with two arguments can be generated (e.g. 3-rd param being optional or ParamArray or whatever) otherwise the resolution continues traversing outer scopes for symbol + number of parameters match.

Btw, I'm really curious how is this going to be fixed in TB.

**Comment by WaynePhillipsEA** [comment]
It gets complicated very quickly, because for example you could have a property called Left that returns an object that has a default-member that takes the arguments...

To makes things even more complicated, you also have to consider overload member resolution.  If for example you have a couple of overloads called DoSomething in a module, the resolver would first bind a call to DoSomething to the **_group_** of overloads in that module first purely based on the symbol name and taking into account of scoping rules, and then disambiguates between the overloads, in only that module, based on the arguments provided.

It's not impossible to solve, but needs some thought how best to handle it.

**Comment by OldestCoderInTown** [comment]
s = vba.Left$(s, 4)

That's a cure.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 65.  Thanks!
