### ISSUE TITLE
Build fails due to unrecognised symbol (Method) of Late Bound object

### ISSUE THREAD

**Issue by AntsAntix** [WaynePhillipsEA/twinbasic#541]
**Describe the bug**
Code that previously had a successful build now fails due to errors
**To Reproduce**
With Component.CodeModule
	Index = .CountOfDeclarationLines + 1
	Do While Index < .CountOfLines
		m.Procedures = m.Procedures + 1
		Name = .ProcOfLine(Index, Kind)
		m.NamesLen = m.NamesLen + Len(Name)
		Index = .ProcStartLine(Name, Kind) + .ProcCountLines(Name, Kind) + 1
	Loop
End With
... method ProcOfLine is not recognised while others such as CountOfLines are recognised.
A plethora of methods and properties related to VBE and VBIDE are handled successfully.

**Expected behavior**
That twinBASIC should resolve this reference in the same way as sibling methods for the same library

**Screenshots**
![image](https://user-images.githubusercontent.com/89644755/145174759-6ac00d48-a3a3-4110-8eea-d8338a8f6040.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.3.24]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
This is a conflict due to the Name-As statement now being implemented (notice that 'Name =' appears in blue meaning that it is being interpreted as a statement keyword).   There are some known conflicts with using keywords as variable names (#115).  The VBx compiler is hard-coded to allow for many of these conflicts, and we will now have to go through each keyword/reserved word to copy the VBx compiler behaviours in this regard.

As a temporary fix, please use the 'Let ' prefix, so `Let Name = .ProcOfLine(Index, Kind)`

**Comment by WaynePhillipsEA** [comment]
v0.13.25 fixes the Name-As syntax clash, and so this issue should now be resolved.  Thanks for reporting.
