### ISSUE TITLE
VS Code or a new, tailored Twinbasic IDE?

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#572]
How I see this.... The best part of VB6 is the simple and very handy, fast, integrated IDE, and that is why VB6 could survive in the last 20 years. Time proved this concept.

A few projects have already tried to "rewrite" and upgrade VB6, the best try for me was the Jabaco which was very handy with its 100% VB6 analogue IDE. Unfortunately its developer suddenly left/abandoned the project.
The Xojo or the B4x are also good ideas, but because of theirs poor form designer, and complicated GUI they never win the match on the market. (and because of the lack of real VB6 compatibility)

Twinbasic is a very promising project, and I hope very very much that it can be a working, real life product, which can finally take over the flag from VB6. 
Maybe I am wrong, but I think, the average person who is still interested in VB6 (and now Twinbasic), is a middle aged (or even older?) person, who used the VB6 IDE for ages, and they will continue theirs Vb6 written projects "as is", without much pain. With a modernized IDE and even with new extra functions of course, but at first mainly in the same practical framework.
(And if the Twinbasic can become a good tool, even young, new developers can choose it)

This VS Code can do the job now as a demo project, but very complicated, not handy, and lacks everything which is good and simple in the original VB6. I dont know how much better can Theia be, but I think a good and easy to use, VB6 style IDE is as important as a good and 100% VB6 compatible compiler, if you want to win with this project (which I hope :) )

**Comment by camomille22003** [comment]
Like VisualFreeBasic (not 100% compatible), but it's a titanic job :
###############################################################
The origin of VisualFreeBasic
Since the birth of FreeBASIC for more than ten years, its IDE has been in the state of a code editor, and there is no automatic processing. Novices have no way to start, and they simply cannot know where to start. Until 2015, the FireFly software developed by Paul Squires (nationality: Canada) appeared, which greatly simplified FB programming, so that novices can also use FB to write software.
Although FireFly has brought great progress to FB's IDE, many of them are not satisfactory. So at the end of 2016, Yongfang began to patch FireFly for more than 2 years. Because there is no source code, only DLL combined with plug-in technology can be used. Come to fix it. Researching FireFly also gradually accumulated a lot of experience in IDE.
Patched from FireFly 3.X, it has been changed for more than 2 years and it has been very mature, named VisualFreeBasic 4.X, but because there is no IDE source code, it can not continue to improve and add better functions, so it started in June 2019 from zero At the beginning, I used VFB4 to write VFB5. After 5 months (with experience and imitating, and using a lot of code written for FireFly before, I wrote it in a short time. If there is nothing, it will be written by Yongfang alone. It is estimated that at least 1 year), a stable test version was released, and VisualFreeBasic5 was born. Programming is endless, life is endless, and improvement is endless. VisualFreeBasic will get better and better.
##############################################################
![IDE_VFB5](https://user-images.githubusercontent.com/33807881/146374239-cbecbf18-3a3c-4d22-8572-709a1de0c039.jpg)

**Comment by WaynePhillipsEA** [comment]
Starting from scratch would be a disastrous idea!  Theia is very much like VS Code, but allows for more customization.  It will allow us to easily strip down the unnecessary bits of the IDE and will allow us to provide an IDE that is more familiar to VBx developers.

I'm closing this in favour of #458... please discuss there.  Thanks.
