### ISSUE TITLE
Compiler crashing

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#602]
**Describe the bug**
My lastest edits to my TwinLib64 library project have once again reduced the compiler to tears.  Over the past week the compiler has been getting increasingly fractious, with restarts needed 5 or 6 times an hour of editing.  Its now pulled up stumps completely and is giving the following message

![CompilerCrashing](https://user-images.githubusercontent.com/81257042/147403763-575fa9bf-9048-49e6-b2af-9c6882bc2cdd.jpg)

Prior to this error message appearing the compiler tries to restart several times

Zipped project is attached.

[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7776771/TwinLib64.zip)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [0.13.56]

**Comment by WaynePhillipsEA** [comment]
Crash fixed in v0.13.57, thanks for reporting.

For the regular restarting issue, I suspect it's due to a memory leak that is building up as you are editing.  It looks like every key stroke in your project is causing a leak of about 0.5MB, which would quickly build up during a normal editing session.  I will look at this memory leak later this week.
