### ISSUE TITLE
Implements from typelib for non-HRESULTs

### ISSUE THREAD

**Issue by Kr00l** [WaynePhillipsEA/twinbasic#605]
**Is your feature request related to a problem? Please describe.**
In VBx it is only possible to implement HRESULT interfaces.
tB allows to an extent but raises problems afterwards.

**Describe the solution you'd like**
Would it be possible to allow this ? Thus providing better flexibility than VBx.
For example to implement interfaces that return LONG.
For intrinsic class interfaces this is possible in tB. (and also VBx) It just is an issue from typelibs.

**Describe alternatives you've considered**
n/a

**Additional context**
![image](https://user-images.githubusercontent.com/33756666/147463399-70e32745-1f78-4b2a-9abd-caf33bc6b298.png)

**Comment by WaynePhillipsEA** [comment]
Yes, this is possible, though not as simple as it sounds.   We'd have to make the non-HRESULT implemented members be stubs that forward to the normal HRESULT based implementations (on the root class vtable), discarding the HRESULT (assuming no error) and returning the last implicit Out/Byref argument as the real (Long) return value.   If an error occurs (indicated by the HRESULT), we'd have to treat it as an unhandled error (since no error propagation is possible).

This is probably one to look at after v1.

**Comment by bclothier** [comment]
I think this issue can be closed because we already have a solution for this (c.f. https://github.com/WaynePhillipsEA/twinbasic/issues/25#issuecomment-1112877560 ).
