### ISSUE TITLE
Generated ActiveX DLLs need to support DllRegisterServer and DllUnregisterServer

### ISSUE THREAD

**Issue by WaynePhillipsEA** [WaynePhillipsEA/twinbasic#61]
**Describe the bug**
twinBASIC generates ActiveX DLLs that don't yet support DllRegisterServer / DllUnregisterServer.

**Expected behavior**
twinBASIC should implement DllRegisterServer and DllUnregisterServer appropriately.

**Additional context**
Currently, the compiler / IDE registers the generated DLLs type library and coclass information in the registry directly at build-time, but this needs to be moved to the DLL so that regsvr32 can be used to register DLLs correctly on end-user machines during installation.

**Comment by WaynePhillipsEA** [comment]
This is a known limitation with the preview release.  Reported here so that we can track it.

**Comment by bclothier** [comment]
Linking #22 because there are discussion that touches on the project type and exporting functions.

Also for consideration: It is my understanding that `regsvr32` wants to write the information into HKLM when we might want to use HKCU. That is particularly true when using the library code in a locked down corporate environment. I agree that supporting `regsvr32` is great but we need to also make sure `regsvr32 /i:install` can be supported as well to enable the HKCU registration. Note that the `install` is just a convention since `regsvr32` has no notion of real HKCU registration so we'll need to override the default behavior of `regsvr32` somehow.

**Comment by WaynePhillipsEA** [comment]
Regsvr32 just calls our DllRegisterServer function, so we are free to implement as we see fit.   The version that is currently implemented by the IDE/compiler registers to the HKCU hive.  We may want an option in the project settings to allow for HKCU (our default), or HKLM

**Comment by bclothier** [comment]
Hmm, I was under the impression that `regsvr32` will perform functions behind the scene such as registering type library and thus fail if not run elevated. If that's not the case, great!

**Comment by WaynePhillipsEA** [comment]
Nope, it's all down to us

**Comment by WaynePhillipsEA** [comment]
So from v0.9.2443, ActiveX DLLs generated by twinBASIC do implement DllRegisterServer and DllUnregisterServer.

There are actually two different implementations available.  The default implementation uses the HKEY_CURRENT_USER registry hive, but you can switch it to use the HKEY_LOCAL_MACHINE registry hive in the project settings:

<img width="679" alt="RegisterDllOption" src="https://user-images.githubusercontent.com/25738109/117168357-f8d50180-adbf-11eb-8f4f-4246740f247e.png">
Of course be aware that the HKEY_LOCAL_MACHINE implementation requires elevated permissions ('Run as admin' etc), whereas the HKEY_CURRENT_USER one does not.

AND, we can also now do custom registrations by defining DllRegisterServer/DllUnregisterServer in your twinBASIC project:

<img width="305" alt="RegisterDllCustom" src="https://user-images.githubusercontent.com/25738109/117168921-831d6580-adc0-11eb-9bbd-d4ff98bfdfc8.png">

These custom registrations are **in addition** to the usual registrations, not instead of.  If you return False from these callbacks, the DLL registrations will fail at runtime.

**Comment by WaynePhillipsEA** [comment]
And finally, if you want to unregister the DLL from within VS code, you can use a new command:
F1 > "twinBASIC: clean build (deregister & delete built files)"
In future this will assigned to a button in the twinBASIC panel.

**Comment by Kr00l** [comment]
> These custom registrations are **in addition** to the usual registrations, not instead of. If you return False from these callbacks, the DLL registrations will fail at runtime.

Nice. So the callbacks are called "before" or "after"?
If "before", then the registration is aborted if the return value is False.
Or it will proceed if there is no custom function or the return value is True?
If my understanding is correct, wouldnt it make more sense to abort only if the custom implementation is True? (Like Cancel = True)
So having none custom function or returning False would be the same.
Or do I missunderstand something?

**Comment by bclothier** [comment]
Also, what is the plan to allow for custom implementation that may need to override the default behavior? 

Not sure I have a example that absolutely requires overriding, especially if we would be able to control the shape of type library via attributes.

**Comment by WaynePhillipsEA** [comment]
@Kr00l for DllRegisterServer, the normal registrations are done first, and then if they succeed, your custom DllRegisterServer will be called, if you've defined one.

For DllUnregisterServer, the process is done backwards, so DllUnregisterServer is called first, and then the normal registrations get deregistered last.

Admittedly, it might be better to offer both 'before' and 'after' events for both cases, to give the most flexibility.

**Comment by WaynePhillipsEA** [comment]
@bclothier Not really considered that.  If we can think of a reasonable scenario where that might be useful, I'm listening.

**Comment by bclothier** [comment]
In my past uses, it was just to work around limitations of the .NET (e.g. decorating `[restricted]` attribute to the type library), but this doesn't mean tB can't do that. I suppose the earlier idea of having a "Before" event where we can choose to override the default registration in its entirety would be the simplest way to give the flexibility without overcomplicating things. That implies a `Cancel` wouldn't be sufficient; you want `Response As RegistrationActionEnum` with `Cancel`, `UseDefaultRegistration` and `RegistrationHandled` or something similar. 

It's my hope that it will be rare to need to override the default registration behavior simply by using attributes which is much more cleaner way of shaping the type library, IMO.

**Comment by Kr00l** [comment]
Just a question.
Would it be possible to introduce a third setting for "Register DLLs" setting?
The third setting would be "try and error" approach. IF write access to HKLM exists, write there, if not then write to HKCU.

**Comment by WaynePhillipsEA** [comment]
I think that's a good idea @Kr00l

**Comment by wqweto** [comment]
I think @Kr00l's idea should be the default mode of operation and even skip the project option altogether but allow registration target hive to be customized in code only (in the callback functions for instance) or something even more obscure :-))

**Comment by Kr00l** [comment]
> I think @Kr00l's idea should be the default mode of operation and even skip the project option altogether but allow registration target hive to be customized in code only (in the callback functions for instance) or something even more obscure :-))

Wayne suggested a drop-down setting. So why not have those options:
1. HKLM if possible, else HKCU (default)
2. HKCU always
3. HKLM only, fail otherwise

**Comment by wqweto** [comment]
How will this option affect unregistration too? When default will unregistration remove entries both from HKLM annd HKCU hives if both present?

**Comment by Kr00l** [comment]
> How will this option affect unregistration too? When default will unregistration remove entries both from HKLM annd HKCU hives if both present?

My logic would say:
If HKLM exists, try to remove..
..if success, then remove HKCU as well (if present)
..if HKLM fails, abort all (HKCU remains if present) to prevent inconsistency from the original intent.

If HKLM does not exist, just remove HKCU.

The above scheme should work for all settings/modes.

**Comment by wqweto** [comment]
For which setting value is this logic suitable?

It looks like for complete reg keys removal the DLL has to be unregistered twice.

**Comment by Kr00l** [comment]
For all, as said.
If HKLM "exists" then this would a barrier. HKCU would only be unregistered also if HKLM was successfull.

**Comment by bclothier** [comment]
FWIW, while I think having the ability to register HKLM if possible then fallback to HKCU is a good idea, I'm not 100% sure it's the best default due to a gap in how this is handled by admin/standard. There are reports where the registration will fail to load for standard user because it was registered by admin. I can't find the Microsoft blog that discusses this issue specifically as it also involves how the registry is redirected. To avoid the problems associated with not finding the registration due to different view of the registry as the result of UAC, it's best to use only HKCU or HKLM and require elevation all the times.

**Comment by Kr00l** [comment]
What's the point for HKCU at all if it needs to be elevated?

**Comment by bclothier** [comment]
No, not saying HKCU requires elevation. As an example, if you register the addin for Office into HKCU, then run Office as admin, that addin won't load because it's not available to the admin. There may be other edge cases associated with mixing the registration vs. the use of the control that can surprise the unwary.

**Comment by Kr00l** [comment]
Agree.
So, having all 3 options is nice.
But the default should be HKLM only, (IMO) as this is the most stable/secure thing and nearly always expected outside in the wild when having a Ax DLL at hand.

**Comment by WaynePhillipsEA** [comment]
One problem with having 'HKLM only' as the default is that you then need to have VS Code elevated in order to register the DLL during development.

**Comment by Kr00l** [comment]
> One problem with having 'HKLM only' as the default is that you then need to have VS Code elevated in order to register the DLL during development.

Whatever default has a side-effect.
So the lesser evil must be found.

IMO having HKLM as default is the lesser evil as this just affects VS code compile. If there is somebody who cannot run vs code elevated can opt-in to one of the other two options.

But the benefit for the outside world would be better/more predictable to be 'HKLM only'.

**Comment by bclothier** [comment]
TBH, I actually think HKLM only will hurt adoption of tB solutions. I just don't see it as a viable candidate for Office add-ins. I actually author my stuff to work in HKCU all the time just to not have to worry about the security issues. I think that makes for a better citizen. I know that this is contrary to the practices that was commonplace in big bad wild west 90s but it was the 90s that gave us Melissa and blaster so.... I would rather view HKLM as the last resort and encourage other authors to do the same.

**Comment by Kr00l** [comment]
I do mostly VB6 with having Ax DLLs regfree with SxS. So I don't bother with HKLM also.
The argument with office add-ins is a good one and a blind spot in my view.
So, yes either 'HKCU always' or 'HKLM if possible' should be the default then.

**Comment by WaynePhillipsEA** [comment]
I am all for HKCU being the default, as it already is (though not for when loading VB6 projects, for full compatibility).

The question remains whether we want to introduce the 'HKLM with HKCU fallback' option, but... it feels somewhat clunky, especially when considering that unregistering also then needs to try unregistering in both hives too.  

I just don't want to introduce something that causes more problems that it solves.

**Comment by Kr00l** [comment]
I still like the idea of that option, because if somebody is aware of, enables great flexibility out of the box. But, yes it should not be the default.

**Comment by bclothier** [comment]
FWIW with Rubberduck addin, we support both modes. That requires a boatload of pascal scripting just to support installing to either modes. Pascal!!!! I love me some quiches but that's too much....

**Comment by mansellan** [comment]
Yep, it was kinda essential when Rubberduck got VB6 support, as running the VB6 IDE without elevation is a road to misery.

**Comment by wqweto** [comment]
Can we then name the third option simply "Both" so that it registers both in HKLM and HKCU and on unregister it operates again on both HKLM and HKCU (all the time writing in registry in "On Error Resume Next" mode)?

**Comment by Kr00l** [comment]
> Can we then name the third option simply "Both" so that it registers both in HKLM and HKCU and on unregister it operates again on both HKLM and HKCU (all the time writing in registry in "On Error Resume Next" mode)?

The background of my idea is to "influence" the behavior.
Example I open cmd.exe as user, then it registers to HKCU (as HKLM is not write-able)
If I again open cmd.exe as admin, then it registers to HKLM (ignoring HKCU)

For unregistering it can be the same way.
If somebody wants "both" then hey - just run as user and again as admin. It's that flexibility which I like.

**Comment by bclothier** [comment]
I wouldn't recommend installing to both HKLM and HKCU. We avoid this in our install because that can lead to a inconsistent state that can cause problem in runtime. One or other, never both.

As a matter of fact, the installer will have to check for either modes and if they don't agree. For example, user has installed previous version of Rubberduck in per-machine scope but now wants to install the new version in per-user scope, the installer will ask to uninstall the old version just to avoid problems.

**Comment by Kr00l** [comment]
Just for clarification, to give my last two cents on this topic :) Thanks

The current two option shall remain as there are currently.
So, to summarize my logic: (revised, not clunky)

If 'HKCU' is selected (default) = it will register/unregister to HKCU only.
If 'HKLM' is selected = it will register/unregister to HKLM only.
If 'HKLM > HKCU' is selected (in case it will be included) = it will attempt to register/unregister first on HKLM, if there is an access violation then it will simply fallback to register/unregister to HKCU.

**Comment by wqweto** [comment]
@Kr00l Your 3-rd option needs to persist state between register and unregister. On unregister it has to attempt to delete reg keys only from the hive in which register succeeded.

Suppose a non-admin users registers the DLL in HKCU, then at some point the same user is granted admin rights on the machine and then tries to unregister.

**Comment by Kr00l** [comment]
> @Kr00l Your 3-rd option needs to persist state between register and unregister. On unregister it has to attempt to delete reg keys only from the hive in which register succeeded.
> 
> Suppose a non-admin users registers the DLL in HKCU, then at some point the same user is granted admin rights on the machine and then tries to unregister.

Well, even if you have admin rights. You can run un-elevated to unregister then at HKCU first.

**Comment by wqweto** [comment]
> Well, even if you have admin rights. You can run un-elevated to unregister then at HKCU first.

That's not the point. Which hive unregister will operate on if the DLL is compiled with 3-rd option set?

**Comment by wqweto** [comment]
> If unregister is elevated (= read write access HKLM) then hive is HKLM.
> If unregister is un-elevated then hive is HKCU.

This means that in the use-case above the newly minted admin user will be unable to unregister the HKCU registration they themselves did as regular user (before being promoted to local admin).

**Comment by wqweto** [comment]
> I don't understand. Even as local admin you can run a process "not as admin".

It took me some time to get what you mean as it's a bit unorthodox for me.  I though we were talking about IsAdmin, not IsElevated check all the time.

There is no elevation on XP and on Wine and it never occurred to me a transient flag like IsElevated can be used as a distinguisher.

**Comment by bclothier** [comment]
I agree with @wqweto about needing to store the state for unregister. It's more complicated than just checking for admin/elevated. This is a reason why in Rubberduck's installer, we use 2 different appId, which has the effect of treating a per-machine install as a separate install than a per-user install. During the installer's check, it will check if either appId exists to determine if this is a upgrade rather than new install. In the case of finding a per-machine install, it will ask user to first elevate the installer and thus allow only per-machine install.

But here I'm talking about the installers and this is about the registration of a DLL; the scope is different. I am do not think it's appropriate for the DLL to store state which also makes it fragile (e.g. what if the state is lost), and I am not sure it's also appropriate for the DLL to guess unregistration based on whether it's admin/elevated or not. That seems to be an installer concern, rather than DLL registration concern.

**Comment by bclothier** [comment]
Thinking about it some more, I'm more inclined toward the idea that this need to be an explicit choice rather than implicit based on the state. Example:

Registers into HKCU: `regsvr32 foo.dll`
Registers into HKLM: `regsvr32 /i:HKLM foo.dll`

Unregisters from HKCU: `regsvr32 /u foo.dll`
Unregisters from HKLM: `regsvr32 /u /i:HKLM foo.dll`

It then becomes the user's responsibility to select the correct mode, and it's left up to the user how to store the registration state --- using an installer or something. If the user wants to be extra sure, the user may need to call `regsvr /u` twice, which avoids the need for the DLL to store the state because I don't think that's the DLL's responsibility. I agree that it's not kosher, but think making it an explicit request from user makes it clear what's going on. 

Being explicit ensures that there is no confusion or surprises when we are in an edge case where the IsAdmin or IsElevated may not give the correct picture. XP & Wine already was cited; there's also the fact that some choose to turn off UAC, and then there are weird permission setups where one is quasi-admin. 

The downside is that the `HKLM` would become a reserved command line argument but I think that is not common so shouldn't be a big loss for those who want to make use of the `/i` to control custom registration.

**Comment by Kr00l** [comment]
My only intent was that it would be nice to influence the behavior HKLM<>HKCU dynamically instead of static.
If an `/i HKLM` helps for the potential 3rd option I am with it. :-)

**Comment by DaveInCaz** [comment]
Is there also an option to enable/disable registration at compile time? A lot of the projects I work on having it disabled would be an advantage.

**Comment by WaynePhillipsEA** [comment]
@DaveInCaz do you mean an option to turn off the creation of the DllRegisterServer / DllUnregisterServer exports, and thus cause regsvr32 to fail on those DLLs?   If so, that's not currently an option, but could easily be added.

**Comment by DaveInCaz** [comment]
@WaynePhillipsEA sorry I wasn't more clear; I actually meant just to turn off the automatic registration at build time. If you happen to develop on a PC that also has the app installed then you can run into cases where you have different DLLs registered in different places, or multiple unwanted versions registered, etc. I'd prefer to be able to control any registrations very carefully. I think this also could help junior devs avoid some pitfalls.

That said, not creating the register functions at all could also make sense if the DLL would never be used from COM.

Seems like the "do/do not register after compile" option would be independent of those mentioned [above](https://github.com/WaynePhillipsEA/twinbasic/issues/61#issuecomment-833309016).

But the "do/do not not create register functions" option maybe should be the 4th option in addition to those others..?

**Comment by WaynePhillipsEA** [comment]
Thanks for clarifying @DaveInCaz.  Yes, I think we can offer both of those.

**Comment by Kr00l** [comment]
While we are in Preview still.. :-)
What about the idea to change DllRegisterServer/DllUnregisterServer callbacks?
As bclothier and me suggested, to have these callbacks as Sub instead of Function with these parameters.
`ByVal Stage As Enum (Pre or Post event)`
`ByRef Response As Enum (DoDefault, SkipDefault or Cancel)`

So response `SkipDefault` would mean to handle custom registration entirely.
`DoDefault` would be the default which would allow custom additions, if needed.
Response `Cancel` would abort the process at that stage.

**Comment by WaynePhillipsEA** [comment]
I'm wondering whether it would be cleaner for the custom callbacks to completely override their internal versions, thus making the developer then responsible for doing the usual registration as well as any custom additions.  

The usual registration is quite straightforward to implement... you call RegisterTypeLibForUser (or RegisterTypeLib), and then you manually register the coclasses.  We could expose the coclasses information (progIds and CLSIDs) that need to be registered manually via a simple reflection-like API.  DllRegisterServer then might look something like this (**_air code_**):

```
Function DllRegisterServer() As Boolean

    ' self-register the type library
    Registry.SelfRegisterTypeLibForUser

    ' register coclasses
    For Each coClass In Reflection.Classes
        If coClass.IsCreatable Then
            Registry.CreateValue("HKCU\SOFTWARE\Classes\CLSID\" & coClass.CLSID & "\" & InProcServer32, App.Path)
            Registry.CreateValue("HKCU\SOFTWARE\Classes\" & coClass.ProgId & "\CLSID", coClass.CLSID)
        End If
    Next

    ' now do any further custom registry additions here...

End Function
```

This approach might be simpler?  Thoughts?

**Comment by DaveInCaz** [comment]
Could it generate the code for the default versions of those functions automatically, and then leave it to the programmer to modify them?  Especially the first few times someone wants to customize this, that could save a lot of time & effort yet retain the ability to fully customize.

**Comment by WaynePhillipsEA** [comment]
> Could it generate the code for the default versions of those functions automatically, and then leave it to the programmer to modify them? Especially the first few times someone wants to customize this, that could save a lot of time & effort yet retain the ability to fully customize.

We could include the default implementations as part of the ActiveX DLL templates, and add them automatically if importing from a VBP file.

**Comment by Kr00l** [comment]
When `regsvr32 /i` is used, e.g. `regsvr32 /i:user` then the lptDllCmdLine is passed too DllInstall. Can this be accessed then at the DllRegisterServer/DllUnregisterServer callback?

**Comment by WaynePhillipsEA** [comment]
> When `regsvr32 /i` is used, e.g. `regsvr32 /i:user` then the lptDllCmdLine is passed too DllInstall. Can this be accessed then at the DllRegisterServer/DllUnregisterServer callback?

I don't see why not... sounds sensible

**Comment by bclothier** [comment]
IMHO, I'm not a huge fan of creating a preset module with code in place for the programmer to then tweak. 

I want to make this very easy to use and understandable and I think it'll be more common to want to _extend_ rather than replace the registration behavior. Therefore, it seems to me more 'BASIC' to go from:

1: the programmer adds nothing; therefore, tB provide a default implementation for register/unregistration
2: the programmer creates the handler; the tB provides the default implementation but then calls programmer's defined procedure after the fact, allowing the programmer to extend the default procedure
3: the programmer completely overrides the implementation; tB does nothing whatsoever. 

The point being that when a higher level of control is needed, the programmer has to request it, by passing appropriate parameters into the callbacks and setting specific values to extend or prevent the default behavior. 

Providing a template for the programmer to then tweak means it is now always programmer's responsibility to maintain that registration is correct. Imagine that in future Microsoft decides to change their security policies, which impacts how COM registration are handled. With the template approach, tB wouldn't be able to help because we can't handle customized registration that was hand-tweaked by the programmer. With the default registration approach, tB is free to update the behavior upon recompilation from the programmer. Of course, if the programmer opted to suppress the default, that's on the programmer anyway but it was an explicit choice. 

Thus, for those reasons, I think the default implementation should be a black box for which the programmer must explicitly opt out (or opt to extend upon it).

**Comment by WaynePhillipsEA** [comment]
```
Function DllRegisterServer() As Boolean

    ' self-register the type library and co classes
    Registry.DefaultDllRegisterServer

    ' now do any further custom registry additions here...

End Function
```
Some here were asking for pre- and post- events so the full replacement approach seen above seems more customizable, and allows for custom error recovery etc.

**Comment by bclothier** [comment]
I think that'll work nicely. Don't forget Kr00l's point about passing in the `/i` parameter. I also think we may need some information such whether this is going into HKLM or HKCU and whether the process is running elevated. Currently the choice to use HKLM/HKCU is a project setting, not a in-code setting so that could get messy....

**Comment by WaynePhillipsEA** [comment]
For `/i` I think we should allow to grab it through to Command$, like command line args

Perhaps need to populate a global constant to indicate the HKCU/HKLM project setting.

**Comment by bclothier** [comment]
While those are certainly possible, I should point that they are also less discoverable. An user presented with this for first time will have to be told that they need to use 2 seemingly unrelated functions/constants to get that data. Were they passed as a parameter to the function, there would be no need to ask.

**Comment by WaynePhillipsEA** [comment]
Provided the HKLM/HKCU setting won't be needed to be known outside of the DllRegister calls, we'll go with that.

**Comment by mansellan** [comment]
```
Function DllRegisterServer() As Boolean
   ' do stuff before the default registration

    ' self-register the type library and co classes
    Registry.DefaultDllRegisterServer

    ' now do any further custom registry additions here...

End Function
```

The proposal also allows code to be called before, after (or both) the call to the default registration, or to replace it entirely. Seems fully flexible.

**Comment by bclothier** [comment]
Closing this as resolved.
