### ISSUE TITLE
Package source files are editable & uglified

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#681]
**Describe the bug**
As I understand it, the package source files are intended to be read-only. Yet, VSC let me edit the file and even offer to save it, which fails. 

Furthermore, I get no colors at all it's treated as if it's just a plain old text file with no semantic highlighting.

**To Reproduce**
1. Create & publish a package.
2. In a new project, reference the package
3. Open a source file within the package's folder. 
4. Observe lack of coloring. Try to edit.
5. Try to close the window. VSC then offers to save the changes.

**Expected behavior**
Ideally, it should be highlighted and I cannot even type anything. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - twinBASIC compiler version 0.13.88

**Comment by WaynePhillipsEA** [comment]
Ah OK... this happens when you've added a package but haven't yet saved the Settings file to restart the compiler.   I'll ensure the files get locked immediately once added (without the restart), but it is to be expected that the files will not have semantic highlighting until the package is loaded by the compiler (upon compiler restart).

**Comment by WaynePhillipsEA** [comment]
Package files now become locked immediately as of v0.13.89, thanks
