### ISSUE TITLE
CSharpishFormat: VBA in Excel runs fine but crashed in 32bit twinBasic

### ISSUE THREAD

**Issue by FullValueRider** [WaynePhillipsEA/twinbasic#722]
**Describe the bug**
The code was originally written by Mathieu Guindon at [A CSharpish String.Format formatting helper](https://codereview.stackexchange.com/questions/30817/a-csharpish-string-format-formatting-helper)

As rescued by Greedquest at [Greedquest/VBA-Gems](https://github.com/Greedquest/VBA-Gems)

I've rubberducked this code and fixed the obvious inspections.  The code is working fine in VBA (in excel) but crashes in twinBasic.
**To Reproduce**
Run the example in Module Pootle.

**Expected behavior**
the TwinBasic version should run as per the VBA version.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [e.g. 0.14.10]

**Additional context**
The excel file and twinbasic project are attached.
[StringFormatter.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8034236/StringFormatter.zip)

[String Format.zip](https://github.com/WaynePhillipsEA/twinbasic/files/8034227/String.Format.zip)

**Comment by WaynePhillipsEA** [comment]
Just an informal note, it would be helpful to me if we had slight clarity on the term `crashes`.  If the code throws an unexpected error, let's call that 'throws an error', whereas if it hard-crashes (e.g. a compiler restart) let's call that a `crash`. 

I ran the code in Pootle and it seems to thrown an error on the `If identifier.IsIdentifierMatch(specifier) Then` line.  Is that the problem you're experiencing, or are you seeing a hard crash?

**Comment by WaynePhillipsEA** [comment]
It looks like the issue here is that passing a predeclared class to Collection.Add is not triggering the creation of the class, and so the collection is being populated with `Nothing`s.  

As a temporary workaround, if you 'touch' the predeclared symbols before using them in `InitNumericSpecifiers`, it should fix the problem:

```
    Debug.Print ObjPtr(CurrencySFI)
    Debug.Print ObjPtr(DecimalSFI)
    Debug.Print ObjPtr(GeneralNumericSFI)
    Debug.Print ObjPtr(PercentSFI)
    Debug.Print ObjPtr(FixedPointSFI)
    Debug.Print ObjPtr(ExponentialSFI)
    Debug.Print ObjPtr(HexSFI)
    Debug.Print ObjPtr(RoundTripSFI)
    Debug.Print ObjPtr(NumericPaddingSFI)
    Debug.Print ObjPtr(GenericDateTimeSFI)
    
    Set this.NumericSpecifiers = New Collection
    this.NumericSpecifiers.Add CurrencySFI
    ...
```

**Comment by WaynePhillipsEA** [comment]
BTW, this code is wrong:
`If this.PaddingCharacter = vbNullString Then this.PaddingCharacter = DEFAULT_PADDING_CHAR`

Since the PaddingCharacter field is a fixed-length string (1 character length), the condition (comparison to vbNullString/"") will never evaluate to true.  This will result in string output that contains **vbNullChar** characters rather than the **spaces** that this line of code was meant to correct.  

The problem probably went unnoticed in @retailcoder's code because the immediate window in VBA will print **spaces** for **vbNullChar** characters (but tB currently doesn't do that, so the string will be truncated in the debug console instead).

**Comment by FullValueRider** [comment]
@WaynePhillipsEA .  Thanks for the rapid response, much appreciated.  I feel your pain at my terrible abuse of your baby.  I promise from now onwards I will be more circumspect and refrain from using 'crash' unless the compiler is restarted.

All is now working as expected.

Cheers

**Comment by WaynePhillipsEA** [comment]
No worries.  It's more so that I can prioritize my time most effectively (crashes more important than runtime errors).

Anyway, the predeclared instance problem has now been fixed in v0.14.13.  Additionally, I've changed the Debug Console behaviour so that embedded vbNullChar characters are now displayed as spaces, just like the VBx immediate window handles them.

Thanks!

**Comment by bclothier** [comment]
For the record, I would have considered printing unprintable characters a improvement over VBx's approach. There's been times where the rendering of such characters into spaces is actually unhelpful and I have to do more to inspect the string with such characters. Maybe something like:

```
Sir, this\u0009is\u0013\a\u0010\silly\u0000string.
```

would be a huge improvement. I would think there is no back compat problem since it's a debugger display, rather than a part of the code but I could be wrong...

**Comment by WaynePhillipsEA** [comment]
> does such exist in vs code which is not related to a project itself but to whole twinbasic itself

Yes, we just don't have any such settings exposed yet.  When we've implemented some, they will appear in the File > Preferences > Settings list.
