### ISSUE TITLE
Unable to add listbox to winform example - without doing a SAVEALL

### ISSUE THREAD

**Issue by wopag** [WaynePhillipsEA/twinbasic#739]
**Describe the bug**
Adding a listbox to a form, then adding a control.clear - then execute - returns and exception error

**workaround fix
Do a SAVEALL before execute.

**To Reproduce**
1. open winform example
2. add listbox
3. click into  myform and add   controlx.clear in  sub new()
4. click back to mainmodule - then execute

error:
Private Sub HandleCreate() _
                Handles RootWindowElement.Create
                
            SyncColumns()
            
            If Style = ListBoxConstants.vbListBoxCheckbox Then
                ReDim CheckBoxState(0)
            End If

            ' FIXME could send LB_INITSTORAGE to pre-allocate the storage here
            Dim Item As String
            For Each Item In List_INIT
^^^^ Application-defined or object-defined error    Error Number: -2147467259 (80004005)

                AddItem(Item)
            Next

**Comment by WaynePhillipsEA** [comment]
The `For-Each` bug is fixed in the next build coming later today.

However, there is a slightly different issue here, in that if you run code in the debugger (or clicking the `run XYZ` CodeLens), then unsaved form designs aren't synced correctly before the code runs, resulting in unsaved changes to your form designs not being applied.  I'll open a separate issue for that.

The fix for that one at the moment is to just use the big red 'PREVIEW' button on the form designer, which ensures that the unsaved form design is correctly synced before opening the live form.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in v0.14.24, thanks for reporting.

(the form designer sync issue remains open)
