### ISSUE TITLE
Freezing with "Please wait" never-ending loop (64-bit compiler on Windows 7 64-bit issue)

### ISSUE THREAD

**Issue by DinyaZ** [WaynePhillipsEA/twinbasic#774]
**Describe the bug**
I have installed the Webview2 runtime, then unzipped the newest twBasic, but when I try to open the demo apps, it doesnt happen, comes a neverending loop instead.
Important, look at the three red error messages, which comes even before I select anything.
I cant start a new project, the same "pleasewait".
Only CTRL-ALT-DEL helps to close the twinBasic

**Expected behavior**
1. Load and run the program normally
2. To be able to change the original setups, for example 64bit checkbox, etc, which came up only for the very first time
3. To be able to cancel this neverending "pleaswait"

**Screenshots**
See attached!

**Desktop (please complete the following information):**
 - OS: Windows7  64Bit
 - twinBASIC 0.15.2

**Additional context**
![Image21213,](https://user-images.githubusercontent.com/94013032/161133209-a2f21230-df59-4755-a767-f2560894c388.jpg)

**Comment by WaynePhillipsEA** [comment]
Thanks for the report, and the update @DinyaZ    In the current beta, there's not much error checking in this area.  The freeze when the compiler is crashing will soon be detected and reported rather than freezing like this.

I will have to install Windows 7 64-bit to try to reproduce the problem with the 64-bit compiler, so it might take some time for me to fix that.

**Comment by WaynePhillipsEA** [comment]
Just letting you know that I've now installed Win 7 x64 and reproduced this issue, so expect a fix later this week.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in IDE BETA 24.  Thanks for reporting!
