### ISSUE TITLE
The output should have its version available

### ISSUE THREAD

**Issue by bclothier** [WaynePhillipsEA/twinbasic#854]
**Is your feature request related to a problem? Please describe.**
Currently, a file that's built by twinBASIC does not have its file version populated. Furthermore, we cannot specify the version as a variable in the output.

**Describe the solution you'd like**
There are 2 separate requests:

1) We should have the ability to stamp a file with the project version so that it is available via its FIleVersion, making it easy for us to see which a version file (especially a DLL) is at.

2) We should have the ability to write the build version into the filename as the output using the variable. That is more common for debug builds as it enables the developer to see at the glance what version a file is without having to right-click the properties dialog. 

**Describe alternatives you've considered**
Doing it manually.

**Additional context**
Automatic stamping of the file strongly implies the support of auto-incrementing for the build; we wouldn't want to have a bunch of `1.0.0.0` files spewed around the filesystem.

**Comment by Kr00l** [comment]
Do you mean the VERSIONINFO resource block?

**Comment by bclothier** [comment]
Not sure if that's the same thing but I'm referring to this for the first request:
![image](https://user-images.githubusercontent.com/2367644/169857339-5ff85a35-7fbc-4c6a-ae75-9bcea748781f.png)

The second request would become a part of the build file's name.

**Comment by Kr00l** [comment]
The screenshot you show reads from the VERSIONINFO resource block. (Windows)
So in any file it can be changed w/o recompiling via resourceHacker or so.

**Comment by bclothier** [comment]
Ok, good to know. Since that's mostly informational, not terribly concerned. Does digitally signing the file prevent that?

**Comment by bclothier** [comment]
[Based on this answer](https://reverseengineering.stackexchange.com/a/1408), it does sound like signing the file & verifying the signature would do the trick if one is concerned about such tampering of any resources, including version information. This is technically a separate request from the current issue about embedding the version information from tB project into the VERSIONINFO resource.

**Comment by WaynePhillipsEA** [comment]
Tomorrow I plan to add placeholders `${VersionMajor}`/`${VersionMinor}`/`${VersionRevision}`/`${VersionBuild}` for the `Build Output Path` project setting. 

I also plan to add the auto-increment option for the build version numbers.   The problem is, VB6 did not have the `Build` version number, and so it's auto-increment option bumped up the `Revision` number.  How do we want to handle this in twinBASIC?  For back-compat, we'll need to support auto-increment of the `Revision` number, at least as an option.

**Comment by Kr00l** [comment]
Isn't Build before Revision? Means Revision is the very last digit.

You could offer an auto-increment checkbox and beneath a combo box which let's you choose what to auto-increment. You could offer minor, build and revision as option. Revision may be the default for back-compat. (Import VBP file)

**Comment by WaynePhillipsEA** [comment]
> Isn't Build before Revision? Means Revision is the very last digit.

I've only ever seen Build being the last digit;  Major.Minor.Revision.Build

`Revision` will most definitely be the default for VBP imports.

**Comment by bclothier** [comment]
Can we suggest that a new project created from scratch would default to auto-increment by build, while a project imported from VBP auto-increment by revision?

**Comment by WaynePhillipsEA** [comment]
@Kr00l lol I believe you.   I will need to fix the VERSIONINFO block tomorrow :)

**Comment by bclothier** [comment]
I find it annoying that [win32 doesn't define it well](https://docs.microsoft.com/en-us/windows/win32/api/verrsrc/ns-verrsrc-vs_fixedfileinfo), either.

[Additional reading](https://softwareengineering.stackexchange.com/questions/24987/what-exactly-is-the-build-number-in-major-minor-buildnumber-revision).

**Comment by EduardoVB** [comment]
I think I realize why they left the Build number in zero. Four numbers seems not to be necessary. 
Major, minor and another one are enough. I would stick to Revision and offer optionally to use Build (IDK why someone could need that, but...).

**Comment by AstrocalcVB** [comment]
I think VB has this all wrong and I for one wouldn't mind if some compatibility was broken here. The 0 in the version number has always been an annoyance through the years and while it would make sense to keep the version number sequence on import of a vbp, setting this right as a default standard has to be the way to go.

When looking at programs compiled by others than VB (not sure about other Basic dialects) you typically see Major.Minor.Revision.Build where Build can grow very large as it's never reset to 0 (with exceptions maybe or when Major changes). It simply feels logical and "Basic" to post a public a version history like 2.0.0, 2.1.0, 2.1.1 rather than 2.0.0.0, 2.1.0.0, 2.1.0.1, where you in the first sequence let the build increment by each build but not necessarily publish is except for in the file property dialog - if used. Arguably, using all 4 slots may be seen as overkill but should probably be left as a personal choice, but being forced to use all 4 with a constant 0 - if you want Major.Minor.Revision i.e. 3 slots for version - simply feels wrong by all basic logic!

P.S. I mostly follow quietly at this stage due to lack of time but not interest. However, this one I felt I had to comment on, even if a bit late :-)

**Comment by WaynePhillipsEA** [comment]
In BETA 49:
- fixed: corrected the VERSIONINFO Build/Revision ordering [ https://github.com/https://github.com/WaynePhillipsEA/twinbasic/issues/854#issuecomment-1136307113 ]
- added: project setting 'project.versionAutoIncrement' (None|Revision|Build|Minor|Major, and auto import from VBP)
- added: buildPath/exportPath placeholders: ${VersionMajor}, ${VersionMinor}, ${VersionBuild}, ${VersionRevision}

I believe these new options should now satisfy this request.  Let me know if I've missed anything.

**Comment by Kr00l** [comment]
Small "complain". The ordering in the project settings :D
![image](https://user-images.githubusercontent.com/33756666/170261073-74a0ea22-934a-4a36-bc20-f13e8371a8f8.png)

**Comment by WaynePhillipsEA** [comment]
Yes, I think that's worthy of opening an issue for it.

**Comment by Kr00l** [comment]
Please reopen if I'm mistaken.
